### ISSUE TITLE
Publishing SN via sbt-bintray may be broken.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2274] opened 2021-04-27 04:39 UTC
It looks like the Scala Native build uses sbt-bintray plugin (to publish artifacts?).  Given
that Bintray is about to disappear into the sunset, it may be worthwhile
for someone familiar with the SN artifact publication process to consider
alternatives.

I am not familiar with the capabilities of the sbt-bintray plugin. Does it allow
publication to other places?  If not, at the very least, it should probably
be removed as an SN dependency.

**Comment by sjrd** [comment] 2021-04-27 06:31
Duplicate of #2146.

**Closed by sjrd** 2021-04-27 06:31 UTC
