### ISSUE TITLE
Nested structs yield exception

### ISSUE THREAD

**Issue by tindzk** [scala-native/scala-native#709] opened 2017-05-07 21:46 UTC
The following example leads to a compile-time exception:

```scala
type A = CStruct1[CInt]
type B = CStruct1[A]
def f(ptr: Ptr[B]) = !ptr._1
```

The same happens with any other `CStructN`. Here is the stack trace:

```
scala.scalanative.util.package$UnreachableException$
        at scala.scalanative.util.package$UnreachableException$.<clinit>(package.scala)
        at scala.scalanative.util.package$.unreachable(package.scala:7)
        at scala.scalanative.nscplugin.NirNameEncoding$class.printGlobal$1(NirNameEncoding.scala:118)
        at scala.scalanative.nscplugin.NirNameEncoding$class.printType$1(NirNameEncoding.scala:108)
        at scala.scalanative.nscplugin.NirNameEncoding$class.mangledTypeInternal(NirNameEncoding.scala:127)
        at scala.scalanative.nscplugin.NirNameEncoding$class.scala$scalanative$nscplugin$NirNameEncoding$$mangledType(NirNameEncoding.scala:84)
        at scala.scalanative.nscplugin.NirNameEncoding$class.genMethodName(NirNameEncoding.scala:77)
        at scala.scalanative.nscplugin.NirCodeGen.genMethodName(NirCodeGen.scala:15)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMethod$1.apply(NirCodeGen.scala:280)
        at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genMethod(NirCodeGen.scala:276)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMethods$1.apply(NirCodeGen.scala:262)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMethods$1.apply(NirCodeGen.scala:260)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genMethods(NirCodeGen.scala:260)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genNormalClass(NirCodeGen.scala:190)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genClass$1.apply(NirCodeGen.scala:163)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genClass$1.apply(NirCodeGen.scala:161)
        at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genClass(NirCodeGen.scala:161)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$apply$4.apply(NirCodeGen.scala:140)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$apply$4.apply(NirCodeGen.scala:136)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.apply(NirCodeGen.scala:136)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:467)
        at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:458)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:467)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:425)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.run(NirCodeGen.scala:112)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1508)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1609)
```

**Comment by nadavwr** [comment] 2017-05-14 13:42
The type of `f()` is a "naked" `CStruct1[CInt]`. Scala Native currently only supports addressing structs by reference (i.e. `Ptr[CStruct1[CInt]]`). Issue #555 will (hopefully) eventually allow addressing structs by value.

If you were to try `def f(ptr: Ptr[B]): Ptr[A] = ptr._1` instead, that should work. Note the omission of the exclamation mark.

If your use case requires binding to native library API that uses struct-by-value, you can use [libffi-scala-native](https://github.com/nadavwr/libffi-scala-native).

**Comment by tindzk** [comment] 2017-05-14 14:09
I see. Thanks for pointing this out!

**Comment by densh** [comment] 2017-05-20 15:24
Thanks for the bug report, but the issue itself a duplicate of #555.

**Closed by densh** 2017-05-20 15:24 UTC
Labels: bug, interop
