### ISSUE TITLE
Bug in String.getBytes() => BOM is missing (SN v0.4.0-M2)

### ISSUE THREAD

**Issue by david-bouyssie** [scala-native/scala-native#1669] opened 2019-07-25 09:31 UTC
The ```String.getBytes(charset: java.nio.Charset) ``` has a different behavior in SN v0.4.0-M2 compared to SN v0.3.8.

For instance when doing ```"select x from x".getBytes(java.nio.charset.StandardCharsets.UTF_16)``` :
* in 0.3.8 we get ```FEFF00730065006C00650063007400200078002000660072006F006D00200078```
* in 0.4.0-M2 we get ```00730065006C00650063007400200078002000660072006F006D00200078```

@ochrons reported on gitter that the missing part at the begging "FEFF" corresponds to the byte order prefix.

More information:
- https://docs.oracle.com/javase/8/docs/api/java/nio/charset/Charset.html
- http://www.unicode.org/faq/utf_bom.html#bom4

I don't know what is the expected behavior.

**Comment by densh** [comment] 2019-07-25 09:32
Thanks for the report!

**Comment by david-bouyssie** [comment] 2019-07-25 10:29
I also checked on the JVM and I get a result similar to SN v0.3.x

**Comment by LeeTibbert** [comment] 2019-07-25 17:55
Just a quick status update.  More as I discover it.  This I a "quick end of sprint before I crash"
report, not a full "for publication" 

1) I suspect a code generation fault in UTF_16_Common.scala#encodeLoop.  Next step, after
    a rest, is to check the generated output.

   `encodeLoop` defines a method `loop()`. When that name is used, a block of code
    at the top of the file is simply not executed. It has vanished: no goodbye, no forwarding address.
    the printfs show that this is not simply a matter of the variable `needToWriteBOM`
    somehow being false.
```
 printf(s"\n")
        printf(s"encodeLoop: top - in.remaining: ${in.remaining}\n")
        printf(s"encodeLoop: top - out.remaining: ${out.remaining}\n")
    printf(s"\n")
    printf(s"encodeLoop: top - needToWrinteBOM: ${needToWriteBOM}\n")

if (needToWriteBOM) {
        if (out.remaining < 2) {
          printf(s"encodeLoop: returning OVERFLOW\n")
          return CoderResult.OVERFLOW // scalastyle:ignore                      
        } else {
          // Always encode in big endian                                        
         printf(s"encodeLoop: TOP putting BOM into out\n")
          out.put(0xfe.toByte)
          out.put(0xff.toByte)
          needToWriteBOM = false
         printf(s"encodeLoop: TOP after BOM needToWrinteBOM: ${needToWriteBOM}\\
n")
        }

```
    In the original code, loop() is defined with `@inline` and `@tailrec` annotations.  commenting
    those out does not change the unwanted behavior.

     Several other method in that package use the same `loop` idiom.  Printf statements
     in the UTF-16 loop() show that that one is the one being executed (see below).

    What _does_ change the behavior is changing the name of the method from `loop()`
    to `looP` or `zLoop` or `looop`. (in 3 places).    All works as expected and matches 
    Scala JVM.

**Comment by densh** [comment] 2019-07-25 17:59
@LeeTibbert Sounds like a name mangling bug. I've bumped the priority to blocker. Thanks for the investigation!

**Comment by LeeTibbert** [comment] 2019-07-25 18:00
There is a second, less serious issue in nio/charset/CharsetEncoder, where not enough 
characters are allocated for UTF-16 encodings, so that an expensive second trip
through the encodeLoop() code is made, probably incurring at least one Exception.

I one line of sandbox code and 3 lines of comments to fix that.  Fixing this performance issue
 makes debugging the important no-BOM issue easier because there is one trip through
and the input and output buffer counts come our right.

**Comment by ekrich** [comment] 2019-07-25 18:19
@LeeTibbert That could affect Scala.js as well then. cc/ @sjrd

**Comment by LeeTibbert** [comment] 2019-07-25 18:37
@ekrich  I ran out of day before checking the current scala.js for the buffer size issue.
Thank you for looping @sjrd in.

To my thinking, t is somewhat of a designer's trade-off and guestimate of amortized costs. 
Different designers may have different criteria.

Does one have the 99.9 percent UTF-8 case pay an extra 2 bytes so that the odd UTF-16 does
not have to take an expensive second hit?   Depends upon expected workload... 

If nothing , the simplicity following the code is worth the two bytes, especially
when the original allocation may get grown geometrically...

**Comment by LeeTibbert** [comment] 2019-07-26 00:36
Re-reading my torturous description after a rest I see it needs come re-work.
My goal is to make things easier for others, not to push the river.

1) Rough reproducer, building on the work of others (@martijnhoekstra, @david-bouyssie)
 
```
import java.nio.charset._ // defaultCharset                                     
import java.nio.charset.StandardCharsets.{UTF_8, UTF_16}

      // Simple String("ABC") should also work.
     val buf = Array(0xFE, 0xFF, 0, 65, 0, 66, 0, 67).map(x => x.toByte)
     val dataOut = new String(buf, "utf-16")
  
    // Expect prefix of "FEFF" or first two bytes -2, -1, indicating bigendian                                                
    // That is the behavior in Scala JVM & SN 0.3.8           

    dataOut.getBytes(UTF_16) foreach(x => {printf(s"|${x}| ")})
    printf("\n")
  
   // Scala JVM output:
   // |-2| |-1| |0| |65| |0| |66| |0| |67| 

```

2) Three files in javalib/src/main/scala/niocharset have a def encodeLoop() and each
     of those has its interior def loop().  The correct/intended encodeLoop() in
     UTF_16_Common.scala is getting called: it has printfs other two do not and
     intended output in output buffer, no corruption).  The intended loop() in that
     encode() is getting called (printfs).

3)  The intended encodeLoop() has a structure of roughly:
```
def encodeLoop() {

      code_block

      def putChar()

      def loop()

      loop() 
}
```
The presenting issue is that the initial code_block is not getting called when loop() is 
called loop() but it is when it is called zLoop() or such.

4) After a fix there is a condition that took me a while to figure out.  I mention it to
   aid debugging.  encodeLoop() and its zLoop() will get called twice, in stead of the
  expected once (duplicate printf sequences). 

This was a quite astonishing to me. Why was the flow of execution jumping back to
the top of the file?  What has I messed up? Had I done a non-obvious recursive
call?  Why were not all the bytes being processed by the end of the first call?

I  tracked down the fact that the output buffer is actually 2 bytes short when the
BOM is written, so the first encodeLoop returns with 1 input byte not processed
and is called a second time to process that 1 byte.  


I have plenty of other work but standby to be of assistance in trouble shooting or
testing trial fixes.

When the main issue is fixed in the fullness of time, I will submit a short PR to 
address the inefficient double call.

**Comment by LeeTibbert** [comment] 2020-08-24 22:28
Update: I just ran the reproducer case and it looks like the bug is still there, same workaround still works.   I have a small self-contained .scala reproducer I can send when this Issue gets scheduled at its appropriate time.  

Some of the Zio tests are failing with UTF issues. I am currently focusing on getting Zio fibers to run on SN. When I need a distraction, I may spend some time debugging the UTF failures.  I will not be surprised if I end up back here. If I do,
I will try the workaround above (in my very private world, not for publication).

I mentioned the workaround as an aid to fixing the compiler, not as a suggestion that it be implemented.

**Comment by LeeTibbert** [comment] 2020-08-24 22:31
Oh!  UTF_16_Common.scala originally came from Scala.js.   I checked for changes in the Scala.js original since the SN variant was branched off,  Feb 7, 2018.  Nothing relevant in the encode loop jumped out. It does appear that some small changes will
need to be made for Scala 2.13.

All things in time...

**Comment by WojciechMazur** [comment] 2020-09-16 13:13
I think I've found source of this bug. 
### Mangling names for nested functions 
Let's define two classes that represents CharsetEncoder and UTF_16_Common.Encoder: 
```
abstract class A{
 def loop(): String = ???
 protected def encodeLoop(arg1: Int, arg2: String): String
 final def encode(arg1: Int, arg2: String, arg3: Boolean): String = {
 	def loop(): String = {
  		if(arg3) "hello"
    		else encodeLoop(arg1, arg2)
  }
  loop()	
 }
}
```

```
object B extends A {
	def encodeLoop(arg1: Int, arg2: String): String = {
 		println("init_logic")
   	val bool: Boolean = false
  	def loop(): String = {
   		if(bool) "asd" else arg2 * arg1
   	}
   	loop()
  }
}
```

During `lambdalift` phase of Scala compiler nested functions are moved to top level. During this process each of clousures free variable is represented as function argument. 
In example B above `def loop(): String` is changed into `def loop(arg1: int, arg2: String, bool: Boolean)`
Methods in such format are used to create Sig in NIR format, and we would expect to have following mangled Sigs in output: 
* `D10encodeLoopiL16java.lang.StringL16java.lang.StringE`
* `D6encodeiL16java.lang.StringzL16java.lang.StringE`
* `D6loop$1iL16java.lang.StringzL16java.lang.StringE` 
As you can see there's only 1 `loop$1` method, becouse both loop in `class A` and in `object B` have the same signature (due to clousures free variables transformation). 
 
However if we would compile this we won't find signature for `encodeLoop` - it was probably removed by optimizer because it was never used! 

On the otherside if we'll remove `bool` from `B.loop` logic we'll correctly see 4 signatures  
* `D10encodeLoopiL16java.lang.StringL16java.lang.StringE`
* `D6encodeiL16java.lang.StringzL16java.lang.StringE`
* `D6loop$1iL16java.lang.StringL16java.lang.StringE`
* `D6loop$1iL16java.lang.StringzL16java.lang.StringE`

### Source of the problem 
To find if method is virtual or not and get possible targets given Class and its subclasses are traversed to find if they contain given Sig (as seen in Infos.scala -> Class -> targets(sig) ) 
When we use this method on class of `CharsetEncoder` we'll get two targets: `CharsetEncoder` itself and `UTF_16_Common.Encoder`. Method is recognized as virtual and added to `Meta.vtable`. 
In Lowering phase call to `loop()` of CharsetEncoder (or A in this example) is recognized as virtual and method definition of `UTF_16_Common.Encoder` (or B) is used. This also means we're skipping all the logic and completnes checks from A loop

### Solution
I don't know how to change without breaking all the other stuff yet, but at least we I know how to test it :) 
Anybody knows how Scala/JVM handles this or how it should be handled in here?

**Comment by sjrd** [comment] 2020-09-16 14:41
Oh, so this is because there are `loop$1` methods generated both in the superclass and in the subclass, and they happen to collide? If yes, maybe the following is an even smaller reproduction that doesn't need local defs:
```scala
class A {
  private def foo(x: Int): Int = x + 1
  def bar(x: Int): Int = foo(x)
}

class B extends A {
  private def foo(x: Int): Int = x * 2
  def baz(x: Int): Int = foo(x)
}
```
In that case the two `foo(Int): Int` would collide in the same way, wouldn't they?

The thing is that *private* methods are supposed to live in a separate namespace where they are not visible through inheritance. Unlike public and protected methods, which *override* each other when the same signature is present in a subclass and superclass, private methods create *independent* methods.

It is possible that the NIR does not correctly handle that, and instead treats private methods in the same way as public methods, which makes them clash along the class hierarchy. If that is indeed the problem, then a non-intrusive change would be to change name mangling to encode the full name of the enclosing class into the private method's names. So for example `A.foo` would be mangled into `D13private_A_fooII` instead of `D3fooII` (mangling scheme to be improved, probably). `B.foo` would then be mangled into `D13private_B_fooII` and would therefore not collide with `A.foo`.

Does that make sense?

**Comment by WojciechMazur** [comment] 2020-09-16 15:42
Yeah, that makes sense, and in fact it resolves problem. I'll start to implement this

**Closed** 2020-10-02 12:34 UTC
Labels: blocker, bug, component:javalib, component:tools

**Comment by LeeTibbert** [comment] 2020-10-02 22:20
Thank you both for the fix.  This fix allows me to release space in my brain that the issue had been taking up for a long while.
One less ball in the air.
