### ISSUE TITLE
Extending a class which should bring main() into scope does not work properly

### ISSUE THREAD

**Issue by schrepfler** [scala-native/scala-native#805] opened 2017-06-10 12:46 UTC
This can't run without overriding main and Scala Native, same app works fine on Scala.
https://github.com/schrepfler/scala-native-cli

```
import caseapp._

case class ExampleOptions(
  name: String
)

object Hello extends CaseApp[ExampleOptions] {

  //  needed as scala-native at the moment does not import properly the main from CaseApp
  override def main(args: Array[String]) = super.main(args)

  def run(options: ExampleOptions, arg: RemainingArgs): Unit = {
    println(s"Hello, ${options.name}!")
  }

}
```

**Comment by jonas** [comment] 2017-06-10 13:06
Looks like a duplicate of #375.

**Comment by jonas** [comment] 2017-06-10 13:10
I filled a similar issue yesterday (#801) with a small example and test.

**Comment by densh** [comment] 2017-06-21 14:39
Thanks for the report, this is definitely a bug. Seems to be related but not duplicate of #375 and/or #801.

**Closed** 2021-09-30 07:52 UTC
Labels: component:tools, bug
