### ISSUE TITLE
Can't assign bytes directly to a CString

### ISSUE THREAD

**Issue by cedricviaccoz** [scala-native/scala-native#457] opened 2016-12-21 09:48 UTC
```scala
import scalanative.native._, stdlib._, stdio._

object Test {
def main(args: Array[String]): Unit = {
  	val filePathStr: String = "test/test.txt"
  	val filePath: Array[Byte] = filePathStr.getBytes()
        var pathCopy: CString = stackalloc[CChar](1024)
        val length: Int       = filePath.length
        for (i <- 0 until length) {
           pathCopy(i) = filePath(i)
        }
       pathCopy(length) = '\0'
  }
}
```
This throws an  UnsupportedException : ```can't cast from Class(Top(java.lang.Object)) to Ptr (class java.lang.String)```
Apparently it isn't possible anymore to assign directly bytes value to a CString this way, as the exception seems to be launched by ```pathCopy(i) = filePath(i)```. Trying to assign by pointer arithmetic (``` !(pathCopy + i)```) or casting filePath(i) as a CChar will result in the same exception.

**Comment by densh** [comment] 2016-12-21 10:17
It's an interesting bug. `var pathCopy: Ptr[CChar]` gets captures via an `ObjectRef` due to the fact that pointers are reference types according to Scalac at the moment. 

Might be a duplicate of https://github.com/scala-native/scala-native/issues/367

**Workaround:** use while loop here instead. Anyway for-range loops are strongly discouraged, you should never use those while porting Java code.

**Comment by densh** [comment] 2018-07-17 09:43
This is a duplicate of #367.

**Closed** 2018-07-17 09:43 UTC
Labels: bug, component:tools
