### ISSUE TITLE
Can't cast from Class to Ptr during nativeOptimizeNIR

### ISSUE THREAD

**Issue by jokade** [scala-native/scala-native#939] opened 2017-08-17 10:40 UTC
In the following example, calling `fooWithSeq( Seq(FooBar(1)) )` compiles and links fine, but calling `fooWithCArray( Seq(FooBar(1)) )` throws an exception during `nativeOptimizeNIR`:
```
scala.scalanative.util.UnsupportedException: can't cast from Class(Top(java.lang.Object)) to Ptr (class java.lang.String)
```

```scala
@extern
object lib {
  type id = Ptr[Byte]
  def foo(foos: Ptr[id], count: CInt): CInt = extern
}

object bar {
  trait Foo
  case class FooBar(i: Int) extends Foo

  implicit def fooToId(foo: Foo): id = foo.cast[id]

  // works fine when called with fooWithSeq( Seq(FooBar(1)) )
  def fooWithSeq[T<:Foo](foos: Seq[T]): CInt = Zone { implicit z =>
    val count = foos.size
    val array = stackalloc[id]( sizeof[id] * count)
    for(i<-0 until count)
      !(array + i) = foos(i)
    lib.foo(array,count)
  }

  def withCArray[T<:Foo, R](seq: Seq[T])(f: (Ptr[id],Int)=>R): R = Zone { implicit z =>
    val count = seq.size
    val array = stackalloc[id]( sizeof[id] * count)
    for(i<-0 until count)
      !(array + i) = seq(i)
    f(array,count)
  }

  // compiles when used, but exception during optimizeNIR phase
  def fooWithCArray[T<:Foo](foos: Seq[T]): CInt = withCArray(foos){ (array,count) =>
    lib.foo(array,count)
  }
}

**Comment by matil019** [comment] 2017-08-19 14:28
I think I've found another case. The following piece of code causes the same error at `nativeOptimizeNIR`:

```scala
  private[regex] def toCStringN(str: String,
                                charset: Charset = Charset.defaultCharset())(
      implicit z: Zone): (CString, Int) = {
    val bytes = str.getBytes(charset)
    val cstr  = z.alloc(bytes.length + 1)

    var c = 0
    while (c < bytes.length) {
      !(cstr + c) = bytes(c)
      c += 1
    }

    !(cstr + c) = 0.toByte

    (cstr, bytes.length)
  }
```

Perhaps putting `Ptr` into a tuple causes the error. (FYI: `type CString = Ptr[CChar]`)

**Comment by densh** [comment] 2017-09-04 09:12
Hi @jokade, thanks for the report, this looks like a duplicate of #367

**Closed by densh** 2017-09-04 09:12 UTC
