### ISSUE TITLE
Add official FreeBSD support

### ISSUE THREAD

**Issue by alexdupre** [scala-native/scala-native#1055] opened 2017-10-10 14:36 UTC
With the "recent" changes to scala-native FreeBSD support broke again.

I've identified three issues:
1) clog / clogf / cpow / cpowf functions are not implemented in FreeBSD
2) optional ENODATA / ENOSR / ENOSTR / ETIME error codes are not defined in FreeBSD
3) unw_getcontext called by the fillInStackTrace crashes the program, as if the accessed memory is invalid

I'm not sure what's the best fix or workaround to the above issues.

For 1) and 2) I've commented out the missing functions and constants (complex.c, complex.scala, posix.c, errno.scala), and related tests (CCComplexSuite.scala).
For 3) I've commented out the stack trace filling (Throwables.scala).

With the above changes everything works and all tests (excluding the ones that check the stack trace elements) passes, but perhaps there are better solutions.

**Comment by ekrich** [comment] 2017-10-10 14:55
Regarding 1. above. What version of FreeBSD are you using?

It looks like we are supporting C99 which added complex math. I am not sure of a resolution but I found the following 2 posts.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=216863
https://lists.freebsd.org/pipermail/freebsd-numerics/2013-October/000488.html

**Comment by alexdupre** [comment] 2017-10-10 15:08
I'm on FreeBSD 11, the latest, there isn't any release that has an implementation of such functions. As you have found, there have been discussions about it, but no proposed implementations have been considered good enough and imported.

**Comment by densh** [comment] 2017-10-24 09:15
Hi @alexdupre, thanks for the report wrt regression on FreeBSD. 

Previously, we've been limited to being able to run CI on Mac and Linux due to Travis constraints. We've started migration away from it to Jenkins that is truly cross-platform. This opens a door to running CI on more environments at the same time.

**Comment by densh** [comment] 2017-10-24 09:16
Currently blocked by #1060.

**Comment by alexdupre** [comment] 2021-02-01 08:56
Any update after 3 years and the release of 0.4.0? The issues are still the same.

**Comment by ekrich** [comment] 2021-02-01 16:55
I think that we would need someone to probably step up and see if the issues can be worked through maybe in 3 PRs, one for each issue. The first issue should really be fixed upstream but they could be added locally if that is accepted by the leaders.

**Comment by alexdupre** [comment] 2021-02-04 13:44
Actually the situation is slightly better than 3 years ago, and I was able to make good enough patches that might be committed directly to scala-native repo. I'll open a pull request soon, after fixing a few tests.

**Comment by alexdupre** [comment] 2021-02-04 16:42
Have a look: https://github.com/scala-native/scala-native/pull/2148

**Comment by ekrich** [comment] 2021-12-02 16:37
@WojciechMazur I am not sure if this is "Official" FreeBSD support but we have install directions so I'm assuming it works so I think it might be good enough to close this ticket. https://scala-native.readthedocs.io/en/latest/user/setup.html#environment-setup

**Closed** 2021-12-02 16:38 UTC
Labels: os:freebsd
