### ISSUE TITLE
`nir_2.12-0.4.5` contains `object scala.scalanative.nir.Attr#Volatile` ?

### ISSUE THREAD

**Issue by armanbilge** [scala-native/scala-native#2733] opened 2022-07-17 00:50 UTC
```
$ wget https://repo1.maven.org/maven2/org/scala-native/nir_2.12/0.4.5/nir_2.12-0.4.5.jar
$ less nir_2.12-0.4.5.jar | head -n 30
Archive:  nir_2.12-0.4.5.jar
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
     313  Defl:N      134  57% 2010-01-01 00:00 7a5fd22e  META-INF/MANIFEST.MF
       0  Stored        0   0% 2010-01-01 00:00 00000000  scala/
       0  Stored        0   0% 2010-01-01 00:00 00000000  scala/scalanative/
       0  Stored        0   0% 2010-01-01 00:00 00000000  scala/scalanative/nir/
       0  Stored        0   0% 2010-01-01 00:00 00000000  scala/scalanative/nir/serialization/
     417  Defl:N      290  31% 2010-01-01 00:00 f7899198  scala/scalanative/nir/Attr$.class
    1820  Defl:N      864  53% 2010-01-01 00:00 dfc78456  scala/scalanative/nir/Attr$Abstract$.class
    1892  Defl:N      886  53% 2010-01-01 00:00 59db779c  scala/scalanative/nir/Attr$AlwaysInline$.class
    1788  Defl:N      793  56% 2010-01-01 00:00 726d452d  scala/scalanative/nir/Attr$BailOpt$.class
    2527  Defl:N     1129  55% 2010-01-01 00:00 b43f92d8  scala/scalanative/nir/Attr$BailOpt.class
    1862  Defl:N      882  53% 2010-01-01 00:00 133414b7  scala/scalanative/nir/Attr$DidOpt$.class
    1800  Defl:N      858  52% 2010-01-01 00:00 aec48f49  scala/scalanative/nir/Attr$Dyn$.class
    1812  Defl:N      867  52% 2010-01-01 00:00 6c34053d  scala/scalanative/nir/Attr$Extern$.class
     394  Defl:N      249  37% 2010-01-01 00:00 64b578ea  scala/scalanative/nir/Attr$Inline.class
    1884  Defl:N      885  53% 2010-01-01 00:00 8468c10b  scala/scalanative/nir/Attr$InlineHint$.class
    1759  Defl:N      792  55% 2010-01-01 00:00 c4a0dac7  scala/scalanative/nir/Attr$Link$.class
    2466  Defl:N     1114  55% 2010-01-01 00:00 2e5faa8c  scala/scalanative/nir/Attr$Link.class
    1880  Defl:N      884  53% 2010-01-01 00:00 6ef85883  scala/scalanative/nir/Attr$MayInline$.class
    1904  Defl:N      886  54% 2010-01-01 00:00 0ab5f1e1  scala/scalanative/nir/Attr$MaySpecialize$.class
    1876  Defl:N      883  53% 2010-01-01 00:00 c214d065  scala/scalanative/nir/Attr$NoInline$.class
    1858  Defl:N      881  53% 2010-01-01 00:00 283e0d03  scala/scalanative/nir/Attr$NoOpt$.class
    1900  Defl:N      888  53% 2010-01-01 00:00 a9941b7b  scala/scalanative/nir/Attr$NoSpecialize$.class
     385  Defl:N      252  35% 2010-01-01 00:00 43ebc6f6  scala/scalanative/nir/Attr$Opt.class
     406  Defl:N      257  37% 2010-01-01 00:00 2b4e539b  scala/scalanative/nir/Attr$Specialize.class
    1804  Defl:N      862  52% 2010-01-01 00:00 96740da1  scala/scalanative/nir/Attr$Stub$.class
    1858  Defl:N      882  53% 2010-01-01 00:00 16ba7d85  scala/scalanative/nir/Attr$UnOpt$.class
    1820  Defl:N      864  53% 2010-01-01 00:00 6e091ab9  scala/scalanative/nir/Attr$Volatile$.class
```

However, the sources at v0.4.5 contain no such class.
https://github.com/scala-native/scala-native/blob/7b76278fcebe84704dd3509e62efd6090067202a/nir/src/main/scala/scala/scalanative/nir/Attrs.scala#L11-L33

It looks like it's defined in https://github.com/WojciechMazur/scala-native/pull/23:
https://github.com/scala-native/scala-native/blob/cfa8407f059b47b9e9d819c3820a3db571e2ecd0/nir/src/main/scala/scala/scalanative/nir/Attrs.scala#L33

Perhaps like v0.4.5 was published against an unclean workspace? So it is a chimera with v0.5.x dev branch

**Comment by armanbilge** [comment] 2022-07-17 00:56
Same problem for 2.11 artifact.
```
$ wget https://repo1.maven.org/maven2/org/scala-native/nir_2.11/0.4.5/nir_2.11-0.4.5.jar
$ less nir_2.11-0.4.5.jar | grep Volatile
    1864  Defl:N      892  52% 2010-01-01 00:00 b6a48d13  scala/scalanative/nir/Attr$Volatile$.class
```

**Comment by WojciechMazur** [comment] 2022-07-18 12:46
Thank you for investigating this, it's strange since we use always force `clean` before releasing in the `publish-impl` script, but it's possible that for some reason some files remained in the workspace. Soon we'd need a release 0.4.6 with fixes for compilation using Scala 3.2.x so it would be a good test for checking if the same results would re-appear (of course before publishing artifacts)

**Comment by keynmol** [comment] 2022-07-18 14:59
Would an untracked source file be the cause of this? Wouldn't be covered by `sbt clean`, and would be still compiled by SBT.

Something like `git clean -nx .` can help check whether something that is not checked in is still present in the workspace.

**Comment by armanbilge** [comment] 2022-07-18 15:10
@keynmol so actually I began by investigating the source jars to see if it matches matches the bytecode, but actually they are inconsistent (the sources match v0.4.5 and not v0.5.x).

**Closed** 2022-09-01 20:11 UTC
