### ISSUE TITLE
Optimizing in debug mode produces warnings on JUnit test

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#2012] opened 2020-11-16 20:11 UTC
Remove the comments `/* */` around the imports and inside the test body and compile `scala.scalanative.regex.ExecTest`.

Run as shown in the following output:

```
sbt:scala-native> tests/testOnly scala.scalanative.regex.ExecTest
[info] compiling 7 Scala sources to /Users/eric/workspace/scala-native/unit-tests/target/scala-2.12/classes ...
[info] compiling 197 Scala sources to /Users/eric/workspace/scala-native/unit-tests/target/scala-2.12/test-classes ...
[info] Linking (2574 ms)
[info] Checking intermediate code (1322 ms)
[info] Dumping intermediate code (linked) (2921 ms)
[info] Discovered 4744 classes and 30631 methods
[info] Optimizing (debug mode) (8577 ms)
[warn] Found 1 errors on @"M19java.io.PrintStreamD6formatL16java.lang.StringLAL16java.lang.Object_L19java.io.PrintStreamEO" :
[warn]   0000  didopt def @"M19java.io.PrintStreamD6formatL16java.lang.StringLAL16java.lang.Object_L19java.io.PrintStreamEO" : (@"T19java.io.PrintStream", @"T16java.lang.String", array[@"T16java.lang.Object"]) => @"T19java.io.PrintStream" {
[warn]   0001  %40000(%1 : @"T19java.io.PrintStream", %2 : @"T16java.lang.String", %3 : array[@"T16java.lang.Object"]):
[warn]   0002    %50002 = ieq[@"T16java.lang.Object"] %1 : @"T19java.io.PrintStream", null
[warn]   0003    if %50002 : bool then %60000 else %70000
[warn]   0004  %70000:
[warn]   0005    jump %180000
[warn]   0006  %60000:
[warn]   0007    jump %160000
[warn]   0008  %160000:
[warn]   0009    %160001 = classalloc @"T30java.lang.NullPointerException"
[warn]   0010    %160002 = fieldstore[bool] %160001 : !?@"T30java.lang.NullPointerException", @"M19java.lang.ThrowableF18writableStackTracePT19java.lang.Throwable", true
[warn]   0011    %160003 = fieldstore[bool] %160001 : !?@"T30java.lang.NullPointerException", @"M19java.lang.ThrowableF17enableSuppressionPT19java.lang.Throwable", true
[warn]   0012    %160004 = call[(@"T19java.lang.Throwable") => @"T19java.lang.Throwable"] @"M19java.lang.ThrowableD16fillInStackTraceL19java.lang.ThrowableEO" : ptr(%160001 : !?@"T30java.lang.NullPointerException")
[warn]   0013    jump %170000
[warn]   0014  %170000:
[warn]   0015    throw %160001 : !?@"T30java.lang.NullPointerException"
[warn]   0016  %180000:
[warn]   0017    %180001 = module @"T17java.util.Locale$"
[warn]   0018    %180002 = call[(@"T17java.util.Locale$") => @"T16java.util.Locale"] @"M17java.util.Locale$D10getDefaultL16java.util.LocaleEO" : ptr(%180001 : !?@"T17java.util.Locale$")
[warn]   0019    if %50002 : bool then %220000 else %230000
[warn]   0020  %220000:
[warn]   0021    %220002 = classalloc @"T23java.lang.StringBuilder"
[warn]   0022    %220003 = arrayalloc[char] int 16
[warn]   0023    %220004 = fieldstore[array[char]] %220002 : !?@"T23java.lang.StringBuilder", @"M31java.lang.AbstractStringBuilderF5valueO", %220003 : !?@"T35scala.scalanative.runtime.CharArray"
[warn]   0024    jump %300000(%220002 : !?@"T23java.lang.StringBuilder")
[warn]   0025  %230000:
[warn]   0026    jump %300000(%1 : @"T19java.io.PrintStream")
[warn]   0027  %300000(%300001 : @"T16java.lang.Object"):
[warn]   0028    %40002 = classalloc @"T19java.util.Formatter"
[warn]   0029    %40003 = fieldstore[@"T20java.lang.Appendable"] %40002 : !?@"T19java.util.Formatter", @"M19java.util.FormatterF4_outO", %300001 : @"T16java.lang.Object"
[warn]   0030    %40004 = fieldstore[@"T16java.util.Locale"] %40002 : !?@"T19java.util.Formatter", @"M19java.util.FormatterF7_localeO", %180002 : @"T16java.util.Locale"
[warn]   0031    %40005 = call[(@"T19java.util.Formatter", @"T16java.lang.String", array[@"T16java.lang.Object"]) => @"T19java.util.Formatter"] @"M19java.util.FormatterD6formatL16java.lang.StringLAL16java.lang.Object_L19java.util.FormatterEO" : ptr(%40002 : !?@"T19java.util.Formatter", %2 : @"T16java.lang.String", %3 : array[@"T16java.lang.Object"])
[warn]   0032    ret %1 : @"T19java.io.PrintStream"
[warn]   0033  }
[warn]   in inst #29 / stored value : 
[warn]     expected @"T20java.lang.Appendable", but got @"T16java.lang.Object"
[warn] 1 errors found
[info] Checking intermediate code (366 ms)
[info] Dumping intermediate code (optimized) (2976 ms)
[info] Dumping intermediate code (lowered) (5226 ms)
[info] Generating intermediate code (10696 ms)
[info] Produced 8 files
[info] Compiling to native code (8967 ms)
[info] Linking native code (immix gc, none lto) (655 ms)
[info] Total (42452 ms)
[info] Starting process '/Users/eric/workspace/scala-native/unit-tests/target/scala-2.12/tests-out' on port '52084'.
skip: NOTE	implicit vs. explicit repetitions : 2009-02-02
  | => tests / Test / nativeLink 42s
skip: NOTE	additional repetition tests graciously provided by Chris Kuklewicz www.haskell.org 2009-02-02

skip: NOTE	null subexpression matches : 2002-06-06

skip: NOTE	all standard compliant implementations should pass these : 2002-05-31

EgrepLiterals.Lowercase

  | => scala.scalanative.regex.ExecTest 29s
```

**Comment by WojciechMazur** [comment] 2020-11-18 16:33
I've tried to reproduce this case, but I've not seen the mentioned warnings. I believe it was fixed in #1980. I remember that when I've worked on it I've received multiple similar warnings due to bug in `Sub.lub` logic. 
However, I've tested it only on Linux (Fedora 32). Maybe there might problems in other OS. 
Can you please check if this problem still occurs on your machine? If it does not report errors we may uncomment this file. Execution of this test suite took ~6 minutes on my machine, so probably it still should be ignored.

**Comment by ekrich** [comment] 2020-11-19 00:29
Indeed it looks resolved, thanks.

**Comment by ekrich** [comment] 2020-11-19 17:12
I think the issue is still present one `2.11` only.

**Closed** 2020-11-28 11:31 UTC
Labels: bug, component:tools
