### ISSUE TITLE
java.util.regex.PatternSyntaxException: Bad perl operato

### ISSUE THREAD

**Issue by olafurpg** [scala-native/scala-native#676] opened 2017-04-27 11:28 UTC
```scala
  val leadingAsteriskSpace =
    Pattern.compile("\n *\\*(?!\\*)", Pattern.MULTILINE)
```
triggers 

```
java.util.regex.PatternSyntaxException: Bad perl operator near index 5

 *\*(?!\*)
     ^
	at java.lang.Throwable::init_java.lang.String_java.lang.Throwable
	at java.lang.Exception::init_java.lang.String_java.lang.Throwable
	at java.lang.RuntimeException::init_java.lang.String_java.lang.Throwable
	at java.lang.IllegalArgumentException::init_java.lang.String_java.lang.Throwable
	at java.lang.IllegalArgumentException::init
	at java.util.regex.PatternSyntaxException::init_java.lang.String_java.lang.String_i32
	at java.util.regex.Pattern$::compile_java.lang.String_i32_bool_java.util.regex.Pattern
	at java.util.regex.Pattern$::compile_java.lang.String_i32_java.util.regex.Pattern
	at org.scalafmt.internal.FormatWriter::init_org.scalafmt.internal.FormatOps
```

**Comment by densh** [comment] 2017-04-28 10:58
Duplicate of #620

**Closed by densh** 2017-04-28 10:58 UTC
