### ISSUE TITLE
Illegal Array cast should throw ClassCastException

### ISSUE THREAD

**Issue by matil019** [scala-native/scala-native#876] opened 2017-06-27 11:32 UTC
Trying to cast an `Array` to another type whose element type is unrelated "succeeds" on Scala Native, where it throws `ClassCastException` on JVM.

Demonstration:

```sandbox/Test.scala
object Test {
  class Foo(x: Int) {
    def foo = x
  }

  def main(args: Array[String]): Unit = {
    val ss = Array("a")
    val fs = ss.asInstanceOf[Array[Foo]]
    println(fs(0).foo)
  }
}
```

JVM:
```
java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to [LTest$Foo;
  at Test$.main(<console>:18)
  ... 32 elided
```

Native:
```
97
```

**Comment by densh** [comment] 2017-06-27 11:33
Duplicate of #858

**Comment by matil019** [comment] 2017-06-27 11:34
Sorry, I couldn't find that.

**Comment by densh** [comment] 2017-06-27 11:35
No worries. 😉

**Closed** 2017-06-27 11:34 UTC
