### ISSUE TITLE
`InetAddresTest.getLocalHost` can fail on MacOS-12

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#3530] opened 2023-10-04 19:01 UTC
1 test is failing in the CI after upgrading MacOS 11 -> 12 in #3529 
Failing test stack trace: 
```scala
[error] Test org.scalanative.testsuite.javalib.net.InetAddressTest.getLocalHost failed: java.net.UnknownHostException: Mac-1696431537341.local: nodename nor servname provided, or not known, took 5.004 sec
[error]     at java.net.InetAddress$.getByNonNumericName$$anonfun$1(InetAddress.scala:349)
[error]     at java.net.InetAddress$$$Lambda$6.apply(InetAddress.scala:417)
[error]     at scala.scalanative.unsafe.Zone$.apply(Zone.scala:29)
[error]     at java.net.InetAddress$.getByNonNumericName(InetAddress.scala:348)
[error]     at java.net.InetAddress$.getByName$$anonfun$1(InetAddress.scala:718)
[error]     at java.net.InetAddress$$$Lambda$8.apply(InetAddress.scala:718)
[error]     at scala.Option.getOrElse(Option.scala:201)
[error]     at java.net.InetAddress$.getByName(InetAddress.scala:686)
[error]     at java.net.InetAddress$.getLocalHost(InetAddress.scala:722)
[error]     at java.net.InetAddress.getLocalHost(InetAddress.scala:722)
[error]     at org.scalanative.testsuite.javalib.net.InetAddressTest.getLocalHost(InetAddressTest.scala:157)
[error]     at org.scalanative.testsuite.javalib.net.InetAddressTest$scalanative$junit$bootstrapper$.invokeTest(InetAddressTest.scala:289)
// end of important part
[error]     at scala.scalanative.junit.JUnitTask.$anonfun$9$$anonfun$1$$anonfun$1(JUnitTask.scala:108)
[error]     at scala.scalanative.junit.JUnitTask$$Lambda$19.apply(JUnitTask.scala:108)
[error]     at scala.scalanative.junit.JUnitTask.catchAll(JUnitTask.scala:235)
[error]     at scala.scalanative.junit.JUnitTask.$anonfun$9$$anonfun$1(JUnitTask.scala:107)
[error]     at scala.scalanative.junit.JUnitTask$$Lambda$20.apply(JUnitTask.scala:112)
[error]     at scala.scalanative.junit.JUnitTask.handleExpected(JUnitTask.scala:175)
[error]     at scala.scalanative.junit.JUnitTask.$anonfun$9(JUnitTask.scala:106)
[error]     at scala.scalanative.junit.JUnitTask$$Lambda$9.apply(JUnitTask.scala:112)
[error]     at scala.scalanative.junit.JUnitTask.runTestLifecycle(JUnitTask.scala:207)
[error]     at scala.scalanative.junit.JUnitTask.executeTestMethod(JUnitTask.scala:97)
[error]     at scala.scalanative.junit.JUnitTask.runTests$1(JUnitTask.scala:43)
[error]     at scala.scalanative.junit.JUnitTask.$anonfun$4(JUnitTask.scala:73)
[error]     at scala.scalanative.junit.JUnitTask$$Lambda$4.apply(JUnitTask.scala:74)
[error]     at scala.scalanative.junit.JUnitTask.runTestLifecycle(JUnitTask.scala:207)
[error]     at scala.scalanative.junit.JUnitTask.executeTests(JUnitTask.scala:32)
[error]     at scala.scalanative.junit.JUnitTask.execute$$anonfun$1(JUnitTask.scala:25)
[error]     at scala.scalanative.junit.JUnitTask$$Lambda$1.applyVoid(JUnitTask.scala:26)
[error]     at scala.runtime.function.JProcedure1.apply(JProcedure.scala:28)
[error]     at scala.Option.foreach(Option.scala:437)
[error]     at scala.scalanative.junit.JUnitTask.execute(JUnitTask.scala:19)
[error]     at scala.scalanative.testinterface.TestAdapterBridge.executeFun$$anonfun$1(TestAdapterBridge.scala:85)
[error]     at scala.scalanative.testinterface.TestAdapterBridge$$Lambda$4.apply(TestAdapterBridge.scala:94)
[error]     at scala.scalanative.testinterface.common.RunMuxRPC.attach$$anonfun$2$$anonfun$1(RunMuxRPC.scala:48)
[error]     at scala.scalanative.testinterface.common.RunMuxRPC$$Lambda$8.apply(RunMuxRPC.scala:48)
[error]     at scala.util.Try$.apply(Try.scala:210)
[error]     at scala.scalanative.testinterface.common.RunMuxRPC.attach$$anonfun$2(RunMuxRPC.scala:48)
[error]     at scala.scalanative.testinterface.common.RunMuxRPC$$Lambda$2.apply(RunMuxRPC.scala:48)
[error]     at scala.scalanative.testinterface.common.RunMuxRPC.newDispatchMap$1$$anonfun$1$$anonfun$2(RunMuxRPC.scala:70)
[error]     at scala.scalanative.testinterface.common.RunMuxRPC$$Lambda$10.apply(RunMuxRPC.scala:70)
[error]     at scala.Option.fold(Option.scala:263)
[error]     at scala.scalanative.testinterface.common.RunMuxRPC.newDispatchMap$1$$anonfun$1(RunMuxRPC.scala:67)
[error]     at scala.scalanative.testinterface.common.RunMuxRPC$$Lambda$11.apply(RunMuxRPC.scala:70)
[error]     at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:455)
[error]     at scala.scalanative.runtime.ExecutionContext$.loop(ExecutionContext.scala:18)
[error]     at scala.scalanative.runtime.package$.loop(package.scala:119)
[error]     at scala.scalanative.testinterface.NativeRPC.loop(NativeRPC.scala:25)
[error]     at scala.scalanative.testinterface.TestMain$.main(TestMain.scala:84)
[error]     at scala.scalanative.testinterface.TestMain.main(TestMain.scala:84)
[error]     at <none>.main(unknown:2)
```

**Comment by LeeTibbert** [comment] 2023-10-06 00:25
I've spent some time studying this Issue.  Unless anybody else is keen to tackle it, I will spend more and
assign it to me.   Glad to step away if someone else wants it.

###### First pass

It appears to me that the test is doing __exactly__ what it is supposed to be doing: detecting that there is
a problem associating the OS or hardware name (Mac-1696431537341.local)  to the network (DNS, 
Domain Name Service) name "nodename nor servname provided, or not known".  

The `getByNonNumeric()` call on the stack and the OS name in the Exception indicate that `unistd.gethostname()`
almost certainly returned non-null.  The Exception most probably comes from error checking just after a/the
 C `getaddrinfo` call.

Two working hypotheses are
1) The network has not been started
2) The local OS name has not been properly configured (yet) in DNS.

That and $7.00+ plus 25% tip will get you a latte, perhaps.

###### Next steps

Given that the problem is happen in CI and with a probably with a mis-configured system, this one
is going to take some time.

1) Does the problem happen when running with JVM?  I no,
    what is JVM returning as the content of the InetAddress?

    If yes, this directs thoughts towards a DNS configuration issue.  From the .local suffix, 
    the Bonjour, zeroconfiguration network daemon may be involved.

2) Does the problem happen with macOS 13? 14?

3) Does the indicated test always fail (synchronous) or is the failure intermittent?
    An intermittent failure would direct attention toward network startup code.
    Is it started?  Has DNS had time to initialize (if the OS name is indeed not provided to it.)

###### Worst case

I have figured out a way to make the `InetAddress.getLocalHost()` code robust to the the apparent 
failure here (by returning garbage, either IPv4/IPv6 wildcard address). That just punts the (configuration) error down
the road, where it will be harder for users to discover.  I prefer to define a time budget for attempting to
discover the underlying defect and only fall back to hackery if I run out of time & patience.

**Closed** 2023-10-13 09:47 UTC
Labels: component:javalib, bug, os:macos

**Comment by LeeTibbert** [comment] 2023-10-13 14:08
Note for future Readers:

PR #3569 is a "clean" final PR, it contains a brief discussion of the fix, but not
much rationale or discovery behind it.

I left some descriptive comments in WIP PR #3551 to capture what I discovered about
the fundamental flaws.  I hope they save someone, perhaps me in six months,
 time and aggravation.
