### ISSUE TITLE
scala-native on cygwin

### ISSUE THREAD

**Issue by staeff777** [scala-native/scala-native#379] opened 2016-11-10 10:05 UTC
I wanted to give cygwin a try. I installed clang and the libgc as well as sbt.

During the compilation process I receive
`[error] No recent installation of clang found at \usr\bin\clang-3.8.
[error] See https://github.com/scala-native/scala-native/blob/master/docs/building.md for details.
[error] (*:nativeLink) No recent installation of clang found at \usr\bin\clang-3.8.
[error] See https://github.com/scala-native/scala-native/blob/master/docs/building.md for details.
[error] Total time: 0 s, completed 10.11.2016 11:00:27`

This is probably a windows/sbt problem. When I run `clang-3.8 -dM -E - < /dev/null`, i can see `#define __DECIMAL_DIG__ __LDBL_DECIMAL_DIG__` .

However, I have no Idea how to solve it.

**Comment by densh** [comment] 2016-11-24 09:40
Currently we don't support Windows officially, but I'll leave this ticket alive in case anyone wants to investigate the issue.

**Comment by kmizu** [comment] 2017-03-15 20:40
@staeff777 To avoid this problem, set `nativeClang` and `nativeClangPP`.  However, the other problem will appear.  See: https://github.com/scala-native/scala-native/issues/113#issuecomment-286867849

**Comment by densh** [comment] 2017-05-20 13:40
Official support for windows is coming in #691, I'm closing this issue as a effective duplicate of #113 that's being fixed by it.

**Closed by densh** 2017-05-20 13:40 UTC
Labels: feature, os:windows
