### ISSUE TITLE
ServerSocket and Socket do not work in nativeMode set to release

### ISSUE THREAD

**Issue by RadoslawDryzner** [scala-native/scala-native#1128] opened 2017-12-29 14:58 UTC
I noticed that setting `nativeMode := "release"` in the build settings for a project and using the class `ServerSocket` doesn't work. Instead, I noticed two incorrect behaviours: when setting a timeout period for the socket, the socket exists with a 134 code after the timeout and with a segfault if a connection was receiver before the timeout.

The following server code is enough to reproduce the error:
```
import java.net._

object Hello extends App {
    val serverSocket = new ServerSocket(5000)
    serverSocket.setSoTimeout(3000)
    serverSocket.accept()
}
```
Running this program on the release mode will produce the result:
```
terminate called after throwing an instance of 'scalanative::ExceptionWrapper'
  what():  std::exception
```
and an exit code of 134.
The correct behaviour would be to see a `SocketTimeoutException` being thrown, which correctly happens in the default debug mode.

If a client is used to connect to the socket before the timeout expires, a sefault appears instead. The following client code can be run after the server has begun execution:
```
object Hello extends App {
  val socket = new Socket(InetAddress.getByName("127.0.0.1"), 4445)
}
```
Then the server will exit with a segfault and 139 exit code. Note that this happens only when the timeout is set, otherwise the socket works as expected.

In both cases, it appears the problem comes from the code that handles the timeout behaviour of a socket. I was able to trace it back to around the place where `FD_ZERO` is called before a call to `select` in the file `PlainSocketImpl.scala` in package `java.net`. However I haven't explored further as to what the problem is exactly.

I'm running on Arch Linux 64 bit with the 4.14.8 kernel version of Linux.

**Comment by shadaj** [comment] 2018-01-01 00:04
I noticed something similar, albeit in debug mode, with ServerSocket on ARM/32bit. `FD_SET` was being passed a nil pointer (`FD_ZERO` was not however) causing the segfault. I worked around this by putting the stack allocation, `FD_ZERO`, and `FD_SET` in a separate method https://github.com/scala-native/scala-native/commit/dfabdfce4b9a367a9b17344b988831c4577ea655.

**Comment by asoltysik** [comment] 2018-01-09 13:43
I am currently looking into this. Inspecting the code in `accept` method of `PlainSocketImpl`, it looks like it's correctly going into the part of code that throws the exception:
``` scala
      val selectRes = select(fd.fd + 1, fdset, null, null, time)
      selectRes match {
        case 0 => {
          println("c1")
          throw new SocketTimeoutException(
            "Accept timed out, "
              + "SO_TIMEOUT was set to: " + timeout)
        }
        case -1 => throw new SocketException("Accept failed")
        case _  => {}
      }
    }
```
"c1" gets printed. Does anyone have an idea why the program might terminate when throwing an exception?

**Comment by shadaj** [comment] 2018-05-06 19:01
Some new information from working on official 32-bit support. When dynamically linking libunwind, on some platforms (at least i386) it replaces system calls for throwing exceptions with alternatives that prevent the exception from being caught. In https://github.com/scala-native/scala-native/pull/1225 I've bundled in LLVM libunwind with Scala Native, which should fix those issues.

**Comment by LeeTibbert** [comment] 2018-05-24 00:58
@shadaj , @ekrich 

I believe that I understand what is causing the problem here.  I have it fixed in my sandbox for nativeMode := release (without a regression in "debug").

The code is pretty complex and I currently have only a limited, symptomatic understanding.
The reported problem shows up in PlainSocketImpl.scala accept only when a timeout is set.
The setting timeout is OK, it is the using of it which causes execution to go down a path which calls select. 

In the existing code, space is allocated on the stack for a, lets call it, array, fd_set. Code executes OK until the TIMEOUT exception is thrown. In current release mode, an exception which I could not catch gets thrown, with little to no helpful info.  My guess is that the stack is getting overrun/blown.

When I change the allocation to Zone.alloc, SocketServerSuite passes in both settings of nativeMode.

To make things interesting, there appear to be two related problems that a comprehensive fix should address:


* the same susceptibility appears to exist in the connect() method in the same file. 
 I am not sure if any current *Suite tests connect with a timeout. If such a test does not exist it needs to be created.

* The code in ServerSocket.scala for accept needs to check that the ServerSocket is not closed before executing acceptImpl.  Socket.scala may have the same issue.

After my brain recovers, I will create a PR for this issue.  The definition of fd_set is pretty tangled, so the time to PR will probably be measured in weeks, not hours. It takes time to poke a Jenga tower and
do no harm.

**Comment by densh** [comment] 2018-08-28 10:07
Lets keep it all in #1319.

**Closed by densh** 2018-08-28 10:07 UTC
