### ISSUE TITLE
Failed to do native link in Scala 2.13.8 with Scala Native 0.4.2

### ISSUE THREAD

**Issue by sequencer** [scala-native/scala-native#2531] opened 2022-01-15 15:15 UTC
Here is my repository:
https://github.com/sequencer/gitakc
When I build with `mill` and `clang` from Arch Linux repo.
I got this error message:
```
1 targets failed
gitakc.native[2.13.8].nativeLink java.lang.ClassCastException: class scala.scalanative.linker.Unavailable cannot be cast to class scala.scalanative.linker.ScopeInfo (scala.scalanative.linker.Unavailable and scala.scalanative.linker.ScopeInfo are in unnamed module of loader mill.api.ClassLoader$$anon$1 @96e44d8)
    scala.scalanative.linker.Reach.fallback$1(Reach.scala:120)
    scala.scalanative.linker.Reach.$anonfun$lookup$8(Reach.scala:132)
    scala.Option.orElse(Option.scala:447)
    scala.scalanative.linker.Reach.lookup(Reach.scala:132)
    scala.scalanative.linker.Reach.reachDefn(Reach.scala:176)
    scala.scalanative.linker.Reach.process(Reach.scala:140)
    scala.scalanative.linker.Reach$.apply(Reach.scala:876)
    scala.scalanative.linker.Link$.apply(Link.scala:13)
    scala.scalanative.build.ScalaNative$.$anonfun$link$1(ScalaNative.scala:35)
    scala.scalanative.build.Logger.time(Logger.scala:35)
    scala.scalanative.build.Logger.time$(Logger.scala:32)
    scala.scalanative.build.Logger$$anon$3.time(Logger.scala:88)
    scala.scalanative.build.ScalaNative$.link(ScalaNative.scala:35)
    scala.scalanative.build.Build$.$anonfun$build$1(Build.scala:65)
    scala.scalanative.build.Logger.time(Logger.scala:35)
    scala.scalanative.build.Logger.time$(Logger.scala:32)
    scala.scalanative.build.Logger$$anon$3.time(Logger.scala:88)
    scala.scalanative.build.Build$.build(Build.scala:55)
    mill.scalanativelib.worker.ScalaNativeWorkerImpl.nativeLink(ScalaNativeWorkerImpl.scala:69)
    mill.scalanativelib.ScalaNativeModule.$anonfun$nativeLink$2(ScalaNativeModule.scala:164)
    mill.define.ApplyerGenerated.$anonfun$zipMap$1(ApplicativeGenerated.scala:5)
    mill.define.Task$MappedDest.evaluate(Task.scala:396)
``` 

I think this might be a bug in Scala Native, but not familiar with Scala Native, so seeking for some help from upstream.

**Comment by ekrich** [comment] 2022-01-15 19:55
Hi @sequencer , Thanks for the report and working with Scala Native. 

Scala Native has to be released to support `2.13.8` and only the latest release `0.4.3-RC2` supports this Scala Version. https://github.com/scala-native/scala-native/compare/v0.4.3-RC1...v0.4.3-RC2

The good thing about `0.4.3-RC2` is that it also supports Scala 3.

**Comment by WojciechMazur** [comment] 2022-01-24 08:51
Actually, 2.13.8 was pack-published for 0.4.1 and 0.4.2, however, it contained some bugs leading to incorrect reporting of missing methods/classes. I probably should be already fixed in the latest 0.4.3 release, or at least we should be able to see which JDK methods are missing now

**Comment by WojciechMazur** [comment] 2022-02-09 00:05
I've tried to reproduce your issue with 0.4.3. After dropping parallel-collections dependency (which cannot be supported until multithreading support would be introduced) it compiles just fine. 
In the `ReleaseFull` mode it was taking too much time, but in ReleaseFast works, it compiles and works just fine. Also in most cases, it's better to use LTO.thin instead of the legacy LTO.full. 

A quick note - mill seems to need version 0.10.0 or higher to work with 0.4.3, due to the changes in how main method is resolved. Apparently it does not check which version of Scala Native is being used

**Closed by WojciechMazur** 2022-02-09 00:05 UTC

**Comment by WojciechMazur** [comment] 2022-02-10 23:31
For Scala Native similarly as in Scala.js you need to use special version of library published with additional files - they hava a native of sjs suffix accordingly. Sbt automatically adds this suffix when using %%% to define dependencies. If I remember correctly in mill you use should use <org>::<name>::<version> for cross platform deps instead of <org>::<name>:<version>

**Comment by sequencer** [comment] 2022-02-11 00:03
Thanks! @WojciechMazur, it works now!
