### ISSUE TITLE
Add support for long double

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#815] opened 2017-06-12 14:06 UTC
This data type is a C/C++ standard type as of C99 and is also used by the `math` and `complex` libraries.

**Comment by densh** [comment] 2017-06-12 14:06
Duplicate of #27

**Closed by densh** 2017-06-12 14:06 UTC

**Comment by ekrich** [comment] 2017-06-12 14:18
Sorry

**Comment by densh** [comment] 2017-06-12 14:20
No worries. ;)
