### ISSUE TITLE
I think the compiler crashes when compiling a certain peace of code

### ISSUE THREAD

**Issue by alex4o** [scala-native/scala-native#1249] opened 2018-06-09 18:08 UTC
This is the crash log: https://gist.github.com/alex4o/4a297f3ca4bc35afe008d899dc3cbd64
This is the code that I think crashes the compiler.
```scala
  def getList(obj: Ptr[Byte], size: Int, get: (Ptr[Byte], CInt) => Ptr[Byte]): List[Ptr[Byte]] = {

    var list: List[Ptr[Byte]] = List()

    (0 until size).foreach(index => {
      list = list :+ get(obj, index)
    })

    list
  }

```

I am also passing a c function as an argument.
```scala
	def enum_info_get_method(Info: Ptr[Byte], N: CInt): Ptr[Byte] = extern
```
I call it like that
```scala
for(method <- getList(info.__ref, GIRepository.enum_info_get_n_methods(info.__ref), (a,b) => GIRepository.enum_info_get_method(a,b))) {}
```

**Comment by densh** [comment] 2018-08-28 10:11
Duplicate of #367

**Closed by densh** 2018-08-28 10:11 UTC
