### ISSUE TITLE
Build basic REPL with  LLDB and language plugin

### ISSUE THREAD

**Issue by zeocio** [scala-native/scala-native#110] opened 2016-05-19 03:40 UTC
It would be nice to have a REPL with support for:
- incremental compilation
- platform standard ABI
- loading/calling C/C++ shared libs
- AST/IR/MC debug/trace/instrumentation
- metadata (typeinfo and debugging symbol) introspection

Such a REPL (even a rudimentary one) can help accelerate many SN dev tasks.

It might be a lot of effort to create a REPL similar to https://root.cern.ch/cling. For a  short term solution, would it be easier to add an SN language plugin to LLDB and reuse most of its runtime/platform support logic? Will probably need to host both libjvm (for scala based expression parser/compiler), liblldb and libllvm in the same process before the SN compiler becomes stable and self-hosting.

**Comment by densh** [comment] 2016-05-19 12:34
The idea sounds great, I'd definitely love to see something like this happen in the future. We need to start with emitting basic lldb-friendly debug information first (https://github.com/scala-native/scala-native/issues/29).

**Comment by densh** [comment] 2016-05-19 13:06
On the other hand, what are the benefits of doing this within `lldb` rather than within `sbt`? We already have initial integration with sbt, and we can add more tasks for introspective purposes quite easily. Getting toolchain off the JVM won't happen overnight as that would imply bootstrapping both scalac and native compilers.

**Comment by zeocio** [comment] 2016-05-19 20:15
The main benefit of lldb is its "target" support, which is platform, ptrace, thread, call stack, dwarf etc. I like your idea of running the main REPL interp loop from sbt/jvm context, where more metadata from compile passes is available. We can still leverage all lldb (and llvm) capabilities via a jni bridge.

We can use lldb to set up and manage a dummy "target" process where the evaluation of IR/MC actually takes place. The Swift language seems to take a similar approach https://swift.org/lldb/#why-combine-the-repl-and-debugger

**Comment by densh** [comment] 2018-01-09 12:32
This looks like a rough duplicate of #29. We should focus LLDB-related discussion there.

**Closed by densh** 2018-01-09 12:32 UTC
Labels: component:sbtplugin, component:tools

**Comment by mullerhai** [comment] 2025-02-13 04:05
> This looks like a rough duplicate of [#29](https://github.com/scala-native/scala-native/issues/29). We should focus LLDB-related discussion there.


Hi densh ,I  want to learn how to debug sn with lldb
