### ISSUE TITLE
UnsupportedException: can't cast from Array(Int,2) to Array(Class(Top(java.lang.Object)),0)

### ISSUE THREAD

**Issue by wookietreiber** [scala-native/scala-native#1175] opened 2018-02-25 19:20 UTC
I'm getting these:

```console
$ nativeLink
[info] Linking (948 ms)
[info] Discovered 1944 classes and 13720 methods
[error] scala.scalanative.util.UnsupportedException: can't cast from Array(Int,2) to Array(Class(Top(java.lang.Object)),0)
[error]         at scala.scalanative.util.package$.unsupported(package.scala:20)
[error]         at scala.scalanative.optimizer.pass.AsLowering.onInst(AsLowering.scala:15)
[error]         at scala.scalanative.optimizer.Pass.$anonfun$onInsts$1(Pass.scala:45)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error]         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
[error]         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error]         at scala.scalanative.optimizer.Pass.onInsts(Pass.scala:45)
[error]         at scala.scalanative.optimizer.Pass.onInsts$(Pass.scala:44)
[error]         at scala.scalanative.optimizer.pass.AsLowering.onInsts(AsLowering.scala:9)
[error]         at scala.scalanative.optimizer.Pass.onDefn(Pass.scala:33)
[error]         at scala.scalanative.optimizer.Pass.onDefn$(Pass.scala:24)
[error]         at scala.scalanative.optimizer.pass.AsLowering.onDefn(AsLowering.scala:9)
[error]         at scala.scalanative.optimizer.Pass.$anonfun$onDefns$1(Pass.scala:22)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error]         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
[error]         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error]         at scala.scalanative.optimizer.Pass.onDefns(Pass.scala:22)
[error]         at scala.scalanative.optimizer.Pass.onDefns$(Pass.scala:21)
[error]         at scala.scalanative.optimizer.pass.AsLowering.onDefns(AsLowering.scala:9)
[error]         at scala.scalanative.optimizer.Optimizer$.loop$1(Optimizer.scala:64)
[error]         at scala.scalanative.optimizer.Optimizer$.$anonfun$apply$4(Optimizer.scala:74)
[error]         at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:112)
[error]         at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:109)
[error]         at scala.collection.parallel.immutable.ParHashMap$ParHashMapIterator.map2combiner(ParHashMap.scala:76)
[error]         at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1052)
[error]         at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
[error]         at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
[error]         at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
[error]         at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1049)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:166)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error]         at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error]         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error]         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error]         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error]         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] (Compile / nativeOptimizeNIR) scala.scalanative.util.UnsupportedException: can't cast from Array(Int,2) to Array(Class(Top(java.lang.Object)),0)
```

---

versions:

sbt 1.1.1
scala 2.11.12
scala-native 0.3.6
llvm/clang 5.0.1

**Comment by wookietreiber** [comment] 2018-02-25 19:32
Interestingly, testing with:

```scala
libraryDependencies += "com.lihaoyi" %%% "utest" % "0.6.3" % "test"
testFrameworks := Seq(new TestFramework("utest.runner.Framework"))
```

works:

```console
$ test
[info] Formatting 8 Scala sources in smash:compile ...
[info] Compiling 9 Scala sources to /tmp/sbt/smash/scala-2.11/classes ...
[info] Done compiling.
[info] Formatting 1 Scala source in smash:test ...
[info] Compiling 1 Scala source to /tmp/sbt/smash/scala-2.11/test-classes ...
[info] Done compiling.
[info] Compiling 1 Scala source to /tmp/sbt/smash/scala-2.11/test-classes ...
[info] Done compiling.
[info] Linking (1143 ms)
[info] Discovered 2164 classes and 14841 methods
[info] Optimizing (1702 ms)
[info] Generating intermediate code (568 ms)
[info] Produced 64 files
[info] Compiling to native code (972 ms)
[info] Linking native code (121 ms)
[info] Starting process '/tmp/sbt/smash/scala-2.11/smash-out' on port '41389'.
[info] -------------------------------- Running Tests --------------------------------
...
```

**Comment by wookietreiber** [comment] 2018-02-25 19:57
Ok, I was able to localize the problem by commenting out parts of the call chain. Whatever happens here should most likely be a compile error, but it shows up only when linking. Can we do something about that?

**Comment by densh** [comment] 2018-03-05 15:42
@wookietreiber Can you share a minimal code that crashes with the same issue? I have a hunch that this might be a duplicate of #555. Are you trying to pass CArray by value anywhere? Stack allocating and passing Ptr[CArray[...]] might resolve the issue.

**Comment by wookietreiber** [comment] 2018-03-17 12:17
Sorry for the long silence. Unfortunately, I rebased that project so hard, that I can't reproduce the exact code that led to this error anymore. I was playing with the **pipe** function and it seems I did something wrong with the `fildes` argument.

At that time, I had a different implementation from the one you have at the moment. Yours is:

```scala
  def pipe(fildes: Ptr[CInt]): CInt = extern
```

I had something like `fildes: CArray[CInt, _2]`, likely without the surrounding `Ptr`. So, I guess, it could have been a duplicate of #555. I think, you can close this one as duplicate.

**Closed** 2018-08-28 09:50 UTC
