### ISSUE TITLE
Code for apparently unused routines is being linked in.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1558] opened 2019-04-24 06:20 UTC
Binary size & initial load speed are both areas of concern.

Issues #1551 & #1557 avoid the 800 pound Gorilla in the room. That is, they do not
address the question of why apparently unused code is being brought in?  PRs for each
of those issues will add to code size when we know that the routines in question
are never called. They were `???` before, so if they were getting called anywhere
in 'test-all', it would have been evident.

I suspect that somebody, perhaps String, brings in Format. Format itself is _huge_
and may be the one bringing in the routines in question. Perhaps via a Locale() call.

I believe the optimizer eliminates code it can not reach.  The simplification of
supporting only Locale.US might allow something to become known at compile
time and not trigger loading a bunch of code because it might get executed.

Understanding who is bringing this code and why may allow a sizeable reduction
in code size and speed up in initial program startup. At the least it would 
show why such reductions were not feasible on this issue.

Guess I am going to have to learn some new skills in order to chase this one.

**Comment by densh** [comment] 2019-05-08 15:13
With #1564 it's trivial to see what brings in stub dependencies (the dependency chain is shown in the error message now). Otherwise this issue looks like a duplicate of #1557.

**Closed by densh** 2019-05-08 15:13 UTC
