### ISSUE TITLE
Add support for java.time._

### ISSUE THREAD

**Issue by danielyli** [scala-native/scala-native#1076] opened 2017-11-10 08:37 UTC
Currently, using `DateTimeFormatter` gives the error:

```
[error] cannot link: @java.time.format.DateTimeFormatter
[error] cannot link: @java.time.format.DateTimeFormatter$
[error] cannot link: @java.time.format.DateTimeFormatter$::ofPattern_java.lang.String_java.time.format.DateTimeFormatter
```

**Comment by danielyli** [comment] 2017-11-10 09:16
Actually, I don't think `java.time._` is supported at all.

**Comment by xuwei-k** [comment] 2017-11-11 01:46
https://github.com/scala-native/scala-native/issues/999

**Comment by densh** [comment] 2018-08-28 09:11
Duplicate of #999

**Closed by densh** 2018-08-28 09:11 UTC
