### ISSUE TITLE
Issue with fastparse library

### ISSUE THREAD

**Issue by gryphis** [scala-native/scala-native#2500] opened 2022-01-04 21:23 UTC
Attached is a small application to convert a special text format, example 'assign.param'. It's using Li Haoyi's fastparse library, which I assume causes the error.

**Works well:** scala-cli run --scala 2.13.6 CfgPar*
**Works well too:** scala-cli compile --native --scala 2.13.6 CfgPar*
**Causes an error:** scala-cli run --native --scala 2.13.6 CfgPar*

> Compiling project (Scala 2.13.6, Scala Native)
> Compiled project (Scala 2.13.6, Scala Native)
> Exception in thread "main" scala.scalanative.linker.LinkingException: Undefined definitions found in reachability phase
>         at scala.scalanative.linker.Reach.reportMissing(Reach.scala:760)
>         at scala.scalanative.linker.Reach.result(Reach.scala:30)
>         at scala.scalanative.linker.Reach$.apply(Reach.scala:771)
>         ...

It would be great to enable the use of the pastparse library.
[scala-cli](https://scala-cli.virtuslab.org/docs/commands/run) is a convenient wrapper for e.g. scala native. I use the current version 0.0.8

Thanks

[cfgnorm-link-error.zip](https://github.com/scala-native/scala-native/files/7810451/cfgnorm-link-error.zip)

**Comment by WojciechMazur** [comment] 2022-01-04 23:03
Thank you for the report, can and for provide reproducer. I belive  it should be already fixed in Scala Native version 0.4.3-RC1 and as far as I know you should be able to specify this version explicity in the next release of scala-cli. I'll test it when it would be published and will report it here

**Comment by WojciechMazur** [comment] 2022-02-09 00:35
When using 0.4.3 the code seems to work just fine, however there were needed some changes to the snippet: 
* fastparse in version 2.2.2 is not published for Scala Native ([Maven repo index](https://repo1.maven.org/maven2/com/lihaoyi/fastparse_native0.4_2.13/)). Bumping version to 2.3.1 should fix the problem. 
* To be able to select version of Scala Native scala-cli needed to be updated to 0.1.0 - it involves some changes to `using directives` 
* I've seen that scala-cli does not use the native version of library I needed to use following snippet to make it work: 
```
scala-cli run --native --native-version 0.4.3 --scala 2.13.8 CfgPar*  -d com.lihaoyi::fastparse_native0.4:2.3.3 
```
Usage of the JVM library instead of the one published for Scala Native was a reason to throw errors in the first place. Unfortunately, it was not obvious in the 0.4.2 release due to the bug in missing symbols reporting. When using correct dependency the snippet links and runs also with Scala Native 0.4.2 and 0.4.1. Due to this fact, I'm closing this issue. 

-----
Question to scala-cli team
@romanowski @alexarchambault @lwronski Current scala-cli reference for Scala Native, neither for Scala.js state how to deal with cross-platform dependencies. I've seen that `:::` part instead of `::` does not work. What should we do in such a case?

**Closed by WojciechMazur** 2022-02-09 00:35 UTC

**Comment by WojciechMazur** [comment] 2022-02-10 11:30
Actually a correct way of using platform-specific artifacts is usage of `::` instead of `:` in the second seperator of dependency, eg. 
`com.lihaoyi::fastparse::2.3.3` is equal to `com.lihaoyi::fastparse_native0.4:2.3.3 ` when using Scala Native 0.4.x
