### ISSUE TITLE
UnsupportedException when using structs with functions with type parameters

### ISSUE THREAD

**Issue by kmltml** [scala-native/scala-native#188] opened 2016-06-20 22:19 UTC
The smallest breaking example i could get is:

``` scala
import scalanative.native._
import scalanative.libc.stdlib._

@struct
class Foo(val ord: CInt)

object Test {
  def main(args: Array[String]): Unit = {
    val bar = identity(new Foo(1))
  }
}
```

It fails at compile-time with `[error] (sandbox/*:nativeLink) scala.scalanative.util.package$UnsupportedException: Inst(Local(src,7),As(Struct(Top(Foo),Vector(I(32))),Local(Local(src,6),Class(Top(java.lang.Object))))) (class scala.scalanative.nir.Inst)`

**Comment by densh** [comment] 2016-06-21 07:02
Thanks for the bug report!

**Comment by densh** [comment] 2017-01-03 16:15
Duplicate of #178

**Closed by densh** 2017-01-03 16:15 UTC
Labels: bug, component:tools, interop
