### ISSUE TITLE
Exception during linking for Zones returning Ptr[Byte]

### ISSUE THREAD

**Issue by jokade** [scala-native/scala-native#1347] opened 2018-09-06 16:42 UTC
The following snippet results in
```scala.scalanative.util.UnsupportedException: can't cast from Class(Top(java.lang.Object)) to Ptr```
 
```scala
object Main {
  def main(args: Array[String]): Unit = {
    val ptr = Zone{ implicit z =>
      val p: Ptr[Byte] = null
      p
    }
  }
}
```

Tested with SN-0.3.8

**Comment by jokade** [comment] 2018-09-07 19:41
@LeeTibbert thanks for the elaboration.

However, I would expect `Ptr[Byte]` to be handled like a value type (like `Int`), so the lifetime of `p` should be irrelevant. This is also confirmed by the fact that the code above links just fine, if I don't put it in a zone.

**Comment by densh** [comment] 2018-09-10 09:04
@jokade Yep, that's the correct expectation, pointers should automatically box behind the scenes. This issues is effectively duplicate of #367 and is tentatively planned for next release (0.4.0).

**Closed by densh** 2018-09-10 09:04 UTC
