### ISSUE TITLE
Cannot mark a `val` extern

### ISSUE THREAD

**Issue by Duhemm** [scala-native/scala-native#536] opened 2017-03-08 14:46 UTC
In nativelib, I had a definition:

```scala
  @name("scalanative_o_rdonly")
  val O_RDONLY: CInt = extern
```

This compiles, links, and everything and can be used, but the value was complete garbage (-443987883 in lieu of 0 in my case)

Changing the definition to

```scala
  @name("scalanative_o_rdonly")
  def O_RDONLY: CInt = extern
```

solves the issue, and `O_RDONLY` has the expected value.

Possible duplicate of #202

**Comment by densh** [comment] 2017-03-10 17:55
Thanks for the report!

**Comment by densh** [comment] 2018-07-17 09:37
Duplicate of #202.

**Closed** 2018-07-17 09:37 UTC
Labels: component:nscplugin, component:tools, feature, interop
