### ISSUE TITLE
CSize should be unsigned

### ISSUE THREAD

**Issue by rwhaling** [scala-native/scala-native#732] opened 2017-05-24 14:04 UTC
It looks like `CSize` should be set to `UWord`, not `Word`, to align with the C and POSIX definitions of `size_t`:
https://github.com/scala-native/scala-native/blob/38fb182049698bf67df5be82ad63a4a3b2817315/nativelib/src/main/scala/scala/scalanative/native/package.scala#L72

This would be a good chance to also introduce a `type CSignedSize = Word` that corresponds to `ssize_t`

Reference:
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_types.h.html

**Comment by Duhemm** [comment] 2017-05-24 14:09
Thanks for the report! This is a duplicate of #519.

**Comment by rwhaling** [comment] 2017-05-24 14:09
Sorry, I should have checked.  Thanks!

**Closed by Duhemm** 2017-05-24 14:09 UTC
