### ISSUE TITLE
Performance problems with scalafmt ported on Native

### ISSUE THREAD

**Issue by jchyb** [scala-native/scala-native#2447] opened 2021-12-07 19:09 UTC
## Reproduction 
For a simple reproduction I made a separate branch: https://github.com/jchyb/scalafmt/tree/performance-problems
It is a scalafmt port to SN with an added Tag.scala file in root, as the problems seem to be the most severe there from what I noticed. This file is a part of scala-native repository, from nativelib (it is a large, generated file).
To quickly reproduce:

`sbt scala-native` - this will create a Scala Native binary in cli/native/target/scala-2.12/scalafmt-cli-out

`cli/native/target/scala-2.12/scalafmt-cli-out Tag.scala`

To run the same with JVM:

`sbt cli/assembly` - this will create a fat jar in cli/jvm/target/scala-2.12/scalafmt.jar

`java -jar cli/jvm/target/scala-2.12/scalafmt.jar Tag.scala`

## Experiments
I tried creating a flame graph as suggested [here](https://scala-native.readthedocs.io/en/latest/user/profiling.html). Since I use MacOS and perf is unavailable there, I used DTrace. I have included the flame graph in the reproduction branch as graph-immix.svg and graph-boehm.svg in root. They both show samples that with a strong majority have ended up in the GC, regardless of one used. I have not been able to find how do they get there. The recorder call stacks tend to record have only 4 calls recorded, something like this:
```
              scalafmt-cli-out`Marker_MarkRoots+0x26a
              scalafmt-cli-out`Heap_Collect+0x1a7
              scalafmt-cli-out`Heap_Alloc+0x2f
              scalafmt-cli-out`_SM36scala.scalanative.runtime.CharArray$D5allociL35scala.scalanative.runtime.CharArrayEO+0xf
               56

              scalafmt-cli-out`Marker_markProgramStack+0xce
              scalafmt-cli-out`Marker_MarkRoots+0x13
              scalafmt-cli-out`Heap_Collect+0x1a7
              scalafmt-cli-out`Heap_Alloc+0x2f
              scalafmt-cli-out`_SM36scala.scalanative.runtime.CharArray$D5allociL35scala.scalanative.runtime.CharArrayEO+0xf
               57

              scalafmt-cli-out`Heap_Recycle+0x3c0
              scalafmt-cli-out`Heap_Alloc+0x2f
              scalafmt-cli-out`_SM36scala.scalanative.runtime.CharArray$D5allociL35scala.scalanative.runtime.CharArrayEO+0xf
               57
```
I have not managed to improve that, but it was basically run with:

```
sudo dtrace -c './scalafmt-cli-out Tag.scala' -o out.stacks -n 'profile-997 /execname == "scalafmt-cli-out"/ { @[ustack(100)] = count(); }'

~/git/hub/FlameGraph/stackcollapse.pl out.stacks | ~/git/hub/FlameGraph/flamegraph.pl > graph.svg
```

## Worth Noting
I helped develop this port. It has not passed the review yet. It is possible that the problems could be with the port itself instead of Scala Native. Knowing this, I tried running the JVM version with the changes introduced for the JVM version, yet the results did not change. This is why I hesitated with filing the issue without any minimizations - it may not be a problem with SN.

**Comment by jchyb** [comment] 2021-12-07 19:22
`sbt scala-native` compiles with release-fast mode and full LTO, release-full compilation takes a large amount of time and memory and the improvements aren't very noticeable there - because of that I really do think the issue is memory related. It is also worth noting that previously I would compile with 2.13 - this was before we knew about the regression and this is also how the flame graphs were generated.

**Comment by WojciechMazur** [comment] 2021-12-30 21:00
Fix #2495 might provide some improvements in this area, I would suggest to test scalafmt with the next release containing fix

**Comment by densh** [comment] 2022-01-15 20:07
I've managed to reproduce @jchyb's instructions to see the state performance on current master.

Experiment configuration: JDK11, -Xms2G, -Xmx2G, AMD 5950x, Immix GC.

Build changes: 
* Changed `LTO.full` to `LTO.thin` since the latter is always better (both performance and compilation time).
* Upgraded SN version to locally published snapshot of master.
* Wrapped `main` of the cli runner to format the same file over and over again to collect multiple measurements.

Results: 
* JVM: 1.51554683s / iteration.
* SN: 1.231397209s / iteration.

Looking at profiles I can confirm that extraneous memory copy of arrays are fully gone now. Good job @WojciechMazur!

**Comment by WojciechMazur** [comment] 2022-01-17 12:35
Based on the densh results I guess we can close this issue

**Closed by WojciechMazur** 2022-01-17 12:35 UTC
