### ISSUE TITLE
Contributor's guide possibly out of date

### ISSUE THREAD

**Issue by kyouko-taiga** [scala-native/scala-native#3489] opened 2023-09-19 15:12 UTC
The contributor guide indicates that the following `sbt` commands are part of the ["normal development workflow"](https://scala-native.org/en/latest/contrib/build.html#normal-development-workflow):
```
> tests/test
> tests/testOnly java.lang.StringSuite
> tests/testOnly *StringSuite
```
I wasn't able to run any of these commands after following the installation instructions. Here is the error I get:
```
sbt:scala-native> tests/test
[error] Expected ID character
[error] Not a valid command: tests (similar: test-tools, test-all, tasks)
[error] Expected project ID
[error] Expected configuration
[error] Expected ':'
[error] Expected key
[error] Not a valid key: tests (similar: test, testOnly, testOptions)
[error] tests/test
[error]      ^
```

This problem occurred on the main branch (https://github.com/scala-native/scala-native/commit/5d28d3eb87046d73b6b9888897d38edbf4b7899b) as well as on [v0.4.15](https://github.com/scala-native/scala-native/commit/2c887efb0544d4f4e214689eb0ef853c572c775b).

**Comment by LeeTibbert** [comment] 2023-09-19 15:46
@kyouko-taiga 

Thank you for taking the time to report.  

Unfortunately, the "Contributor's Guide" is __wildly__
out of date; like by five or six years.

The Contributor's Guide is/was intended for people
making changes to Scala Native itself.  It can be useful
to people trying to use Scala Native but there is probably
more dross than gold in the pages; sorta like radium gradually
vanishing from a valuable sample.

The "Getting Started" Guide and the various Library (java, C, native) guides are not perfect but are reasonably, for most
values of "reasonable", up to date, but not "bleeding edge".
I find SN developers to be quite responsive to questions,
especially to thoughtful or well-researched but not
perfect questions.  I have asked more than my share of
questions so I have a karmic debt there.

These days, the name of the subject project is often/usually
qualified by the Scala Version in use (I believe "sbt> show ScalaVersion" possibly "scalaVersion").

A concrete example.  When I am testing a proposed PR,
I set my java to java 8, then "sbt ++2.12.18; shell"
"sbt> tests2_12/testOnly *.StringTest" .
I use the "*." to avoid having to remember the fully qualified
"muble.testsuite.mumble" full package name.

For scala 3.3, I use "sbt> tests3/testOnly *.ProcessTest" etc.
(I was using ProcessTest this weekend, so I remember the
incantation).

I do the Java 8 step when I am qualifying a PR, because
that is the "minimal supported Java version" used in 
Continuous Integration.

In my development work, I use a mixture of Java 17 (the current Long Term Supported version) and Java 21 (soon, like today, to be the current LTS).   Occasionally I stumble over post-Java-8
methods which are Not-Yet-Implemented in Scala Native
and at least consider taking the hit of a recursive-edit
to implement them (and their tests).

Other people may have more efficient practices, so please
do not let me lead you astray.

Please let me/us know how we might be able to help
you get up and running, especially if you are considering
making contributions to Scala Native itself.

Lee
Old person shaking fist at Contributor's Guide.

**Comment by WojciechMazur** [comment] 2023-09-19 15:46
Good point, there were not updated in a while. I'll try to update them soon.

Currently we use a bit more specific projects layout due to limitations of sbt and the non-trivial dependecies (eg. `scalalib` standard library of Scala 3 depends on stdlib of Scala 2.13, or the sbt plugins depening on toolchain compiled with Scala 2.12) 
Now each project (`MultiScalaProject`) defines N subprojects, one 1 each Scala binary version and 1 additional 1 `-next` for Scala 3 experimental builds (or the rather the Scala Next) for Capture Calculus experimental projects (but these ones are added only when specific env variable is defined). It means that we now get following `tests` projects: `tests2_12`, `tests2_13`, `tests3`, `tests3-next` 

Most of the unit tests can be executed on both JVM and Native: that's where additioanl extension is introduced, so we get eg. `testsJVM3`. 

Typical testing usage might depend from context, but eg. it could be `testsJVM3/test` to check if test passes on the JVM (reference result) and then`tests3/test`. 

However, when working with toolchain there are other places where tests might be defined: 
- `tools`, `toolsJVM` - implementation of toolchain (linker, optimizer, LLVM backend) and its tests
- `nir`, `nirJVM` - implementation of Native Intermiediete Representation 
- `nscplugin` - Scala compiler plugin, tests mostly compiler outputs and ensures compile time errors 

I hope I would make it easier to getting started with codebase before updating the docs

**Comment by LeeTibbert** [comment] 2023-09-19 16:14
```
I hope I would make it easier to getting started with codebase before updating the docs
```

Good plan.  Perhaps just a bold banner comment at the 
top of the Guide stating that it is obsolete, especially,
directory layouts, Under Construction, just for historical
and overall interest?

Otherwise,  removing the gaping pothole all together from
the docset for the while and restoring it when updated.

Another possibility is removing the Contributor's Guide and
replacing it, for the while, with a one page Contributor's Cheat Sheet.  That would take _way_ fewer hours and might stem
the tide.  Just a few: Overall "civilized discourse", "running specific tests".

I am sure that there are enough people who could bike shed
it if a sign were posted: Coming soon, SN Bike Shed.   I could
probably create a simple document this weekend if that
idea appeals.  Just the shell of a document (with a date)
and a couple of cheat sheet lines, to be iterated and improved
by the Community.

I am just trying to take the opportunity of this Issue to figure
out a way forward. I know for certain that I do not have the
time in the near to mid future to detail edit the Contributor's Guide.

Can't do everything at once.  Where is a keen grad
student when one needs one????

**Comment by He-Pin** [comment] 2023-09-19 18:54
I helped to setup the akka/pekko contribution helper message in sbt, I think that's very helpful, and I found I copied from it several times too.

And I experienced this too，@kyouko-taiga, and I am using Windows.

Still new, but I think that can be helpful. 
@LeeTibbert Would you spend sometime to explore the current Akka/Pekko contributions experience？

**Comment by kyouko-taiga** [comment] 2023-09-20 14:45
> I find SN developers to be quite responsive to questions, especially to thoughtful or well-researched but not perfect questions. I have asked more than my share of questions so I have a karmic debt there.

I think the last 24h have demonstrated this observation. Thanks for all these fast answers. The community looks awesome!

I will keep notes of all the roadblocks I find on my journey to setup a working dev environment and hopefully that can serve to shore up the Contributor's guideline, or any other document meant to onboard people.

**Comment by tanishiking** [comment] 2023-10-12 09:14
closing for https://github.com/scala-native/scala-native/pull/3496

**Closed by tanishiking** 2023-10-12 09:14 UTC
