### ISSUE TITLE
Incorrect comparing of Option

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#1834] opened 2020-06-22 08:37 UTC
Let get some example
```
    import java.math.BigInteger

    val bn1 = BigInteger.valueOf(73)
    val bn2 = BigInteger.valueOf(73)

    println(s"Some(bn1) == Some(bn2): ${Some(bn1) == Some(bn2)}")
    println(s"Some(bn1) equals Some(bn2): ${Some(bn1) equals Some(bn2)}")
    println(s"bn1 equals bn2: ${bn1 equals bn2}")
```

scala and scala-js works like this:
```
Some(bn1) == Some(bn2): true
Some(bn1) equals Some(bn2): true
bn1 equals bn2: true
```
and I feel that it is expected behaviour.

Anyway, scala-native-0.4.0-M2 has:
```
Some(bn1) == Some(bn2): false
Some(bn1) equals Some(bn2): false
bn1 equals bn2: true
```

**Comment by sjrd** [comment] 2020-06-22 09:43
This is not about the `Option`, but about the big numbers. It's a duplicate of #1770.

**Closed by sjrd** 2020-06-22 09:43 UTC

**Comment by catap** [comment] 2020-06-22 09:57
@sjrd yeah, it is much better.
