### ISSUE TITLE
improvement idea: autogenerate JVM bindings for Scala.native code

### ISSUE THREAD

**Issue by antonkulaga** [scala-native/scala-native#641] opened 2017-04-16 19:52 UTC
There is often a need to call performance-critical native code from JVM projects. It will be great if one can compile performance-critical code to Scala.native and automatically get bindings to call it from his JVM project (esp. if compiling everything to Scala.native is not possible due to dependencies on Java libs).

**Comment by jonas** [comment] 2017-04-16 22:24
Related to #450

**Comment by antonkulaga** [comment] 2017-04-18 09:25
Looks like I've opened a duplicate

**Comment by densh** [comment] 2017-04-19 08:57
Yep, this one is a duplicate of #450.

**Closed by densh** 2017-04-19 08:57 UTC
