### ISSUE TITLE
The sbt plugin should offer a way to compile C files

### ISSUE THREAD

**Issue by jonas** [scala-native/scala-native#657] opened 2017-04-21 20:58 UTC
It would be useful to allow application and libraries to drop down to C for parts of their implementation, for example to not be blocked by limitations such as the ability to pass structs by value. One example is bindgen which currently need a think C wrapper to use libclang. Another example would be to use a C++ library.

The sbt plugin should provide a setting or task which makes it possible to compile C files and include the resulting object files in the `nativeCompileLL` task used by the linker.

Example code from #642 

```scala
nativeCompileLL += {
  val logger   = nativeLogger.value
  val cwd      = nativeWorkdir.value
  val compiler = nativeClang.value.getAbsolutePath
  val opts     = nativeCompileOptions.value
  val cpath    = (resourceDirectory in Compile).value / "clang.c"
  val opath    = (crossTarget in Compile).value / "clang.o"
  val compilec = Seq(compiler) ++ opts ++ Seq("-c",
                                              cpath.toString,
                                              "-o",
                                              opath.toString)

  val exitCode = Process(compilec, cwd) ! logger
  if (exitCode != 0) {
    println("Failed to compile " + cpath)
  }
  opath
}
```

**Comment by densh** [comment] 2017-04-22 08:47
That's a great idea! Something along the lines of `src/main/c` would be extremely useful. Some challenges in this area:

- [ ] C code has to be included in the distributed jar
- [ ] Static vs dynamic linking with jars that contain C code (we can probably start with static only in the beginning)
- [ ] Given that we'll have all the code (and hence the bitcode), it would be nice to make sure that LLVM can LTO across Scala/C boundary

**Comment by nadavwr** [comment] 2017-05-19 15:37
Hitching a ride on nativeCompileLL to compile native code looks very appealing, but having C source files distributed in otherwise-binary jars might not always be appropriate.

For those cases, Jacob Odersky's [sbt-jni](https://github.com/jodersky/sbt-jni) is very good in this regard. If we put aside the main use case (JNI), it includes [JniNative](https://github.com/jodersky/sbt-jni/blob/master/plugin/src/main/scala/ch/jodersky/sbt/jni/plugins/JniNative.scala), which is useful for building native code from SBT project. It provides the `nativeCompile` task that delegates building native code to CMake. `nativeInit` helps bootstrap the CMake build script -- I've been able to figure it out despite being a CMake newb.

[Here](https://github.com/nadavwr/scala-native-sbt-jni-example) is a sample project.

Shortcomings:
1) Biased towards dynamic libraries, but with @jodersky's cooperation that's just a pull request away.
2) Cross compiling for different operating systems and architectures is a problem left to the library developer.

**Comment by matil019** [comment] 2017-06-05 12:43
Hi, I tried compiling [@nadavwr's sample project](https://github.com/nadavwr/scala-native-sbt-jni-example) with a static library and failed. When invoking `clang++` for linking, `-lprintln` (the custom static library) must come _after_ `target/scala-2.11/native/__empty.ll.o` to resolve the references.

I'm using clang 4.0.0.

A quick fix to sbt-scala-native is:

```a.patch
diff --git a/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala b/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala
index 2823faad..d4cc7aa1 100644
--- a/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala
+++ b/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala
@@ -361,10 +361,9 @@ object ScalaNativePluginInternal {
         librt ++ libunwind ++ linked.links
           .map(_.name) ++ garbageCollector(gc).links ++ regex
       }
-      val linkopts  = links.map("-l" + _) ++ linkingOpts
       val targetopt = Seq("-target", target)
-      val flags     = Seq("-o", abs(outpath)) ++ linkopts ++ targetopt
-      val compile   = abs(clangpp) +: (flags ++ paths)
+      val flags     = Seq("-o", abs(outpath)) ++ linkingOpts ++ targetopt
+      val compile   = abs(clangpp) +: (flags ++ paths ++ links.map("-l" + _))

       logger.time("Linking native code") {
         logger.running(compile)
```

By this change, all `-l` options are appended to the linker arguments after everything else. Confirmed working. But it may be a destructive change (I'm not sure).

**Comment by Andrei-Pozolotin** [comment] 2018-03-21 10:45
`src/main/c` -> `src/main/clang` for readability

**Comment by densh** [comment] 2018-03-21 11:53
@Andrei-Pozolotin The convention is `src/main/$language`, not `src/main/$compiler`. What happens if Scala Native would hypothetically get a non-LLVM/Clang-based backend in the future?

**Comment by ekrich** [comment] 2018-03-21 12:12
@densh Since Scala Native already compiles code in `resources`, will the refactoring of code out of the build plugin already get us very close to this change? Then we could move the code in `resources` to the new `c` directory.

**Comment by densh** [comment] 2018-03-21 12:25
@ekrich Current `nativelib/main/resources` is a workaround for not having a general feature for compilation and distribution of C code within Scala Native projects. Once more general feature is available, we'll use it instead.

**Comment by Andrei-Pozolotin** [comment] 2018-03-21 13:05
@densh right, I just treat `src/main/clang` as better language name :-)

**Comment by LeeTibbert** [comment] 2018-07-15 19:10
Sloshing through the backlog whilst waiting for Travis to give me the all green.

@jonas Is this topic still relevant, especially given your recent pr #1265.

 Can it be covered by an example in the .rst documentation? 

Somewhere I have tucked away some .sbt code  which I copied from an example
on the InterWeb, possibly derived from the Jacob Odersky code mentioned above.

The code uses sbt dependsUpon to ensure that a make program, make itself in my usage,
runs before any .scala files are checked for update.  It then uses the sbt nativeLinkingOptions
to link in the C object code. I am not sure if I ever got the Makefile to run only before link, or
if, during early development, I took the easy way out and always ran it. (Difference is that I and
probably most people do more compiling than linking. Running make only before link saves
some CPU cycles. Those are a concern but less dear than devo realtime minutes.)

This or similar code could be put into an example or the FAQ and might help other people.

If we get the idea down, it makes it easier to find/steal cycles to implement it whilst waiting
for Travis.  Agreed that there is no immediate rush, just trying to cap off recent advances
in Interop.

Your thoughts?

**Comment by ekrich** [comment] 2019-06-22 17:34
I am working on this PR at this time but not quite ready to push it upstream as a [WIP]. The first part I am tackling is compiling the code from a dependency that contains native code. This is similar to what is done right now for `nativelib`.

**Comment by ekrich** [comment] 2019-11-12 00:43
Potential fix for this issue - https://github.com/scala-native/scala-native/pull/1637

**Comment by ekrich** [comment] 2020-03-12 17:34
The following shows the vision of allow each project to have it's own C code.
https://github.com/scala-native/scala-native/issues/1352

**Comment by lolgab** [comment] 2020-03-12 18:04
If we allow to have compile time that are always inlined before link time (even in debug mode) we can have Scala platform specific code without C.
That could be the ideal scenario. Other languages (like Zig and Nim) are rewriting C header files to their languages to have inline functions. I think it's doable in Scala too.

**Closed** 2020-08-08 14:41 UTC
Labels: component:tools, feature, interop
