### ISSUE TITLE
`Files#newDirectoryStream` with a glob pattern returns an empty stream

### ISSUE THREAD

**Issue by iRevive** [scala-native/scala-native#2937] opened 2022-10-23 17:49 UTC
Scala Native version: **0.4.7**
Platform: **MacOS. Darwin  21.6.0 arm64**

The snippet:
```scala
//> using scala "2.13.10"

import java.nio.file.{Files, Paths}
import scala.jdk.CollectionConverters._

object Main {
  def main(args: Array[String]): Unit = {
    val files = Files.newDirectoryStream(Paths.get("."), "*.scala").iterator().asScala.toList
    println(s"Found: $files")
  }
}
```

JVM:
```shell
$ scala-cli example.scala
Compiling project (Scala 2.13.10, JVM)
Compiled project (Scala 2.13.10, JVM)
Found: List(./main.scala)
```

Scala Native:
```shell
$ scala-cli --native example.scala
Compiling project (Scala 2.13.10, Scala Native)
Compiled project (Scala 2.13.10, Scala Native)
[info] Linking (1003 ms)
[info] Discovered 1037 classes and 7698 methods
[info] Optimizing (debug mode) (1497 ms)
[info] Generating intermediate code (980 ms)
[info] Produced 8 files
[info] Compiling to native code (1197 ms)
[info] Linking native code (immix gc, none lto) (61 ms)
[info] Total (4785 ms)
Found: List()
```

**Comment by LeeTibbert** [comment] 2022-10-24 13:36
iRevive.   Thank you for reporting this & sorry that you experienced it.
The minimal reproducer will help.

File system glob handling was introduced in approx February, 2022 in SN version 0.4.4.
So, as you already know, it should be working in 0.4.7. 

There is code in `PatternMatcherGlobTest`  which should match the '*.scala'
` pass("*.ext", "banana.ext")`.  That means any devo debugging this needs
to start with DirectoryStream and see if it is producing files and then
tear apart the chain of calls.

What operating system (and version) are you using? Some of the paths in
unit-tests `PatternMatcherGlobTest` differ by OS.

**Comment by iRevive** [comment] 2022-10-24 14:02
I'm using MacOS, `Darwin 21.6.0, arm64`.

**Comment by LeeTibbert** [comment] 2022-10-24 15:32
Thank you for the version information.  It helps when I am chasing shadows.

Some notes to help solving this.  Using the reproducer above:

Both ScalaJVM and ScalaNative DirectoryStream produce
a Stream of names of the form './local.sbt', note the "./" prefix.

In ScalaJVM this will match the glob "*.sbt". On Scala Native,
the glob _will_not_ match and that entry will get filtered out. 
(Duh! that is what iRevive said in the base note)

The relevant code, before one goes down the glob black hole is

Files.scala 
```
def newDirectoryStream(dir: Path, glob: String): DirectoryStream[Path] = {
    val filter = new DirectoryStream.Filter[Path] {
      private val matcher =
        FileSystems.getDefault().getPathMatcher("glob:" + glob)
/* >>> */      override def accept(p: Path): Boolean = matcher.matches(p)
    }
    newDirectoryStream(dir, filter)
  }
```
One can add tests to PathMatcherGlobTest.scala
```
 @Test def LeetGlob(): Unit = {
    pass("*.sbt", "local.sbt")  // ScalaJVM passes, SN passes                   

    pass("./*.sbt", "./local.sbt") // ScalaJVM rejects, SN passes.              

    pass("*.sbt", "./local.sbt") // ScalaJVM passes, SN fails                   
  }
```

It appear that other possible causes have been factored out and
that glob parsing, specifically of the leading "./" has been indited. 

A future developer chasing this should check the definition of
the leading "*" in "*.sbt".  Is it supposed to match directory
paths as well as leading file name characters?  From
ScalaJVM, apparently yes, but it would be nice to 
have the confirmation of original & foundational definitions.

My mind has spent too much time in regex land and needs to reset
for `glob`.

cc: @jchyb   Are you still around?  Any thoughts here, besides 
                   "I escaped that briar patch once and do not want to go back in"
                    IIRC, you are the glob champion and expert.

**Comment by jchyb** [comment] 2022-10-28 11:42
@LeeTibbert Thank you for the ping, I'll try to fix this today. I imagine we just have to if out the `./` case somewhere, usually `/` serves as a separator for `*` (so `./file.exe` would be matched by `*/*.exe`) and I must have not noticed that the behavior in java stdlib is different here for leading `./` (which I guess makes sense).

**Comment by LeeTibbert** [comment] 2022-10-28 11:59
@jchyb Thank you for looking into this. Keeps weenies like out of your nice clean code.

**Comment by LeeTibbert** [comment] 2023-02-15 19:42
@iRevive  This should be fixed in 0.5.x by PR #3166.  That PR is marked for backport to 0.4.x, but I have not 
built it on that branch.  

This Issue also uncovered an issue in another part of java.nio.file.Files with (not) handling `Paths.get("")`.
So this issue brought benefit.

@jchyb 

Thought I would bring some uplift to your day....

It turns out that your nice clean glob code was innocent, where innocent means "doing the same thing as JVM".
The fix to this Issue was in Files.scala. I added a Test to `PatternMatcherGlobTest` to show that your FSM matched
JVM practice.

**Comment by jchyb** [comment] 2023-02-15 20:36
Wow, incredible work. Thank you! This explains a lot. I remember trying to tackle this one and couldn't reproduce via our jvm/native tests, so I got confused and thought the issue might show itself using a different JVM version. So I thought... "I'll try tomorrow", and the right tomorrow never came... I'll try to at least report my findings next time before I put things into my mental backlog

**Comment by LeeTibbert** [comment] 2023-02-15 20:47
> the right tomorrow never came

You captured the song of my life...

> I'll try to at least report my findings next time before I put things into my mental backlog

Thank you for looking at this when you had the chance and your efforts along the way.  
I figured that you, rightly, had higher priorities.

I must confess my limits that I have not quite figured out how to run the JVM tests.  When I tried
to run my modified PatternMatcherGlobTest and my FilesTest using "sbt> testsJVM3/testOnly" 
things went nowhere fast.  Because I needed to get this puppy done, I did not take the 
interrupt to figure out why not. Someday the right tomorrow will come along and I will take
the time to make it work (or know that it should not).

I suspect being able to run the same test in JVM and SN would save me lots of back & forth
to scastie.

You made a lot of commits during your time on Scala Native and I do not remember seeing
any Issues reported on them!

**Comment by ekrich** [comment] 2023-02-15 21:00
This works for me.
```
sbt:scala-native> testsJVM3/testOnly *FilesTest
```

**Comment by LeeTibbert** [comment] 2023-02-15 21:14
Thank you Eric.    Given your existence proof, I'll give it another shot.

**Comment by iRevive** [comment] 2023-02-16 08:41
Thank you for your time and work!

**Closed** 2023-02-16 09:43 UTC
Labels: component:javalib, bug
