### ISSUE TITLE
backend crash on Option.foreach

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-native/scala-native#636] opened 2017-04-12 14:06 UTC
scala.scalanative.util.package$UnsupportedException: can't cast from Class(Top(java.lang.Object)) to Ptr (class java.lang.String)

in 0.1.0

```
def t: Option[Ptr[CChar]] = None
t.foreach(n => println("got it"))
```

**Comment by densh** [comment] 2017-04-12 14:33
Duplicate of #367

**Closed by densh** 2017-04-12 14:33 UTC
