### ISSUE TITLE
NullPointerException in unoptimized binaries using `scala.math.BigInt.testBit`

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#2897] opened 2022-10-10 14:39 UTC
## Env
Scala Native 0.4.7
Scala 2.13.10

optimizer: disabled

------------------

## Reproducer: 
```Scala
object Test {
  def main(args: Array[String]): Unit = {
    val bigint = BigInt(42)
    try {
      bigint.testBit(-3)
    } catch {
      case _: ArithmeticException => println("ok")
    }
  }
}


```

-----------------

## Output
```
ava.lang.NullPointerException
        at java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)
        at java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)
        at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
        at java.lang.StackTrace$.currentStackTrace(Unknown Source)
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at java.lang.Throwable.<init>(Unknown Source)
        at java.lang.Exception.<init>(Unknown Source)
        at java.lang.Exception.<init>(Unknown Source)
        at java.lang.RuntimeException.<init>(Unknown Source)
        at java.lang.RuntimeException.<init>(Unknown Source)
        at java.lang.RuntimeException.<init>(Unknown Source)
        at java.lang.NullPointerException.<init>(Unknown Source)
        at java.lang.NullPointerException.<init>(Unknown Source)
        at scala.scalanative.runtime.package$.throwNullPointer(Unknown Source)
        at <none>.(Unknown Source)
        at Test$.main(Unknown Source)
        at Test.main(Unknown Source)
        at <none>.main(Unknown Source)
        at <none>.__libc_start_main(Unknown Source)
        at <none>._start(Unknown Source)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$17(ScalaNativePluginInternal.scala:243)
[error]         at scala.Option.foreach(Option.scala:407)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$15(ScalaNativePluginInternal.scala:243)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$15$adapted(ScalaNativePluginInternal.scala:220)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] stack trace is suppressed; run last sandbox2_13 / Compile / run for the full output
[error] (sandbox2_13 / Compile / run) Nonzero exit code: 1
```
Should correctly throw ArithmeticException

**Comment by Bensonater** [comment] 2023-08-16 22:24
I can see that throwing an ArithmeticException is the intended behaviour. However running the code on Scala JVM also throws a NullPointerException

```
java.lang.NullPointerException: Cannot invoke &quot;java.math.BigInteger.testBit(int)&quot; because the return value of &quot;scala.math.BigInt._bigInteger()&quot; is null
	at scala.math.BigInt.testBit(BigInt.scala:503)
	at Test$.main(main.scala:5)
	at Test.main(main.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sbt.Run.invokeMain(Run.scala:143)
	at sbt.Run.execute$1(Run.scala:93)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
	at sbt.Run$.executeSuccess(Run.scala:186)
	at sbt.Run.runWithLoader(Run.scala:120)
	at sbt.Run.run(Run.scala:127)
	at com.olegych.scastie.sbtscastie.SbtScastiePlugin$$anon$1.$anonfun$run$1(SbtScastiePlugin.scala:38)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:31)
	at sbt.ScastieTrapExit$App.run(ScastieTrapExit.scala:258)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by armanbilge** [comment] 2023-08-16 23:15
Scala.js appears to throw `ArithmeticException`.

https://github.com/scala-js/scala-js/blob/2da5417f692955dfc9311e276294d6fa4964f05d/javalib/src/main/scala/java/math/BigInteger.scala#L695

**Comment by Bensonater** [comment] 2023-08-17 20:13
We have that bit of logic as well. 

https://github.com/scala-native/scala-native/blob/24ee38f58138d293e6c2858d591c122559e97a3f/javalib/src/main/scala/java/math/BigInteger.scala#L759-L760

The NullPointerException seems to be thrown before this was hit. Passing in a positive argument to `testBit` works as expected.

**Comment by tanishiking** [comment] 2024-11-22 08:39
It seems like this is a bug of the Scala library itself introduced from https://github.com/scala/scala/pull/9628, not a compiler bug :

```scala
// BigInt.scala
  /** Returns true if and only if the designated bit is set.
   */
  def testBit(n: Int): Boolean =
    if (longEncoding && n >= 0) {
      if (n <= 63)
        (_long & (1L << n)) != 0
      else
        _long < 0 // give the sign bit
    } else _bigInteger.testBit(n)
```

[BigInt#testBit refers to _bigInteger](https://github.com/scala/scala/blob/ff5c1546fc11b7ae9f5f7b37192000a5dc9f9c4b/src/library/scala/math/BigInt.scala#L504) which is a [mutable field](https://github.com/scala/scala/blob/ff5c1546fc11b7ae9f5f7b37192000a5dc9f9c4b/src/library/scala/math/BigInt.scala#L179) initialized by  [BigInt#bigInteger](https://github.com/scala/scala/blob/ff5c1546fc11b7ae9f5f7b37192000a5dc9f9c4b/src/library/scala/math/BigInt.scala#L215-L222).

Here, `testBit` should refer `_bigInteger` through `BigInt#bigInteger`, otherwise `_bigInteger` isn't initialized in a normal path and `_bigInteger.testBin` leads to `NullPointerException`.

Actually, the same code throws `NullPointerException` rather than `ArithmeticException` in all platforms (JVM/JS/Native)

## JVM

```sh
$ scala-cli
Downloading Scala 3.2.2 compilerrg/scala-lang/scala-library/maven-metadata.xml
Welcome to Scala 3.2.2 (17.0.6, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> val bigint = BigInt(42)
val bigint: BigInt = 42

scala> bigint.testBit(-3)
java.lang.NullPointerException: Cannot invoke "java.math.BigInteger.testBit(int)" because the return value of "scala.math.BigInt._bigInteger()" is null
  at scala.math.BigInt.testBit(BigInt.scala:503)
  ... 32 elided
```

## Scala.js

Running the same code in Scala.js:

```
org.scalajs.linker.runtime.UndefinedBehaviorError: java.lang.NullPointerException
    at $throwNullPointerException (/Users/tanishiking/ghq/github.com/tanishiking/scala-js/examples/helloworld/.2.13/target/scala-2.13/helloworld-fastopt/main.js:59:9)
    at $n (/Users/tanishiking/ghq/github.com/tanishiking/scala-js/examples/helloworld/.2.13/target/scala-2.13/helloworld-fastopt/main.js:63:5)
    at $c_s_math_BigInt.testBit__I__Z (/Users/tanishiking/ghq/github.com/tanishiking/scala-js/examples/helloworld/.2.13/target/scala-2.13/helloworld-fastopt/https:/raw.githubusercontent.com/scala/scala/v2.13.13/src/library/scala/math/BigInt.scala:504:31)
    at $c_Lhelloworld_HelloWorld$.main__AT__V (/Users/tanishiking/ghq/github.com/tanishiking/scala-js/examples/helloworld/.2.13/target/scala-2.13/helloworld-fastopt/file:/Users/tanishiking/ghq/github.com/tanishiking/scala-js/examples/helloworld/src/main/scala/helloworld/HelloWorld.scala:15:21)
    at $s_Lhelloworld_HelloWorld__main__AT__V (/Users/tanishiking/ghq/github.com/tanishiking/scala-js/examples/helloworld/.2.13/target/scala-2.13/helloworld-fastopt/file:/Users/tanishiking/ghq/github.com/tanishiking/scala-js/examples/helloworld/src/main/scala/helloworld/HelloWorld.scala:11:8)
    at /Users/tanishiking/ghq/github.com/tanishiking/scala-js/examples/helloworld/.2.13/target/scala-2.13/helloworld-fastopt/main.js:6263:1
    at /Users/tanishiking/ghq/github.com/tanishiking/scala-js/examples/helloworld/.2.13/target/scala-2.13/helloworld-fastopt/main.js:6264:4
    at Script.runInThisContext (node:vm:136:12)
    at Object.runInThisContext (node:vm:316:38)
    at [stdin]:8:25
```

<details>
<summary>I confirmed the generated NIR / LLVM IR doesn't have a problem</summary>

```scala
// linker.hnir
def @"M20java.math.BigIntegerD7testBitizEO" : (@"T20java.math.BigInteger", int) => bool {
%3(%2 <this> : @"T20java.math.BigInteger", %1 <n> : int):
  %4 <digit> = var[int]
  %5 <intCount> = ashr[int] %1 <n> : int, int 5
  %10 = ieq[int] %1 <n> : int, int 0
  if %10 : bool then %6 else %7
```

```scala
// optimized.hnir
didopt def @"M20java.math.BigIntegerD7testBitizEO" : (@"T20java.math.BigInteger", int) => bool {
%3000000(%1 <this> : @"T20java.math.BigInteger", %2 <n> : int):
  %3000004 = ieq[int] %2 <n> : int, int 0
  if %3000004 : bool then %4000000 else %5000000
%4000000:
  // ...
%5000000:
  %5000002 = slt[int] %2 <n> : int, int 0
  if %5000002 : bool then %8000000 else %9000000 // should jump to arithmetic exception
%9000000:
  // ...
%8000000:
  jump %18000000
%18000000:
  2: %18000001 = classalloc @"T29java.lang.ArithmeticException"
  2: %18000002 = fieldstore[bool] %18000001 : !?@"T29java.lang.ArithmeticException", @"M19java.lang.ThrowableF18writableStackTracePT19java.lang.Throwable", true
  2: %18000003 = fieldstore[bool] %18000001 : !?@"T29java.lang.ArithmeticException", @"M19java.lang.ThrowableF17enableSuppressionPT19java.lang.Throwable", true
  2: %18000004 = fieldstore[@"T16java.lang.String"] %18000001 : !?@"T29java.lang.ArithmeticException", @"M19java.lang.ThrowableF1sPT19java.lang.Throwable", "Negative bit address"
  13: %18000005 = call[(@"T19java.lang.Throwable") => @"T19java.lang.Throwable"] @"M19java.lang.ThrowableD16fillInStackTraceL19java.lang.ThrowableEO" : ptr(%18000001 : !?@"T29java.lang.ArithmeticException")
  jump %19000000
%19000000:
  throw %18000001 : !?@"T29java.lang.ArithmeticException"
}

```

```llvm
define i1 @"_SM20java.math.BigIntegerD7testBitizEO"(ptr %_1, i32 %_2) personality ptr @__gxx_personality_v0 !dbg !2899 {
_3000000.0:
  call void @llvm.dbg.value(metadata ptr %_1, metadata !2900, metadata !101), !dbg !2904
  call void @llvm.dbg.value(metadata i32 %_2, metadata !2905, metadata !101), !dbg !2904
  %_40000003 = icmp ne ptr %_1, null ; if %_1 is not null
  br i1 %_40000003, label %_40000001.0, label %_40000002.0 ;; not null -> 40000001.0 / null -> %_40000002.0 -> null pointer exception
_40000001.0:
  %_3000004 = icmp eq i32 %_2, 0 ;; n == 0
  br i1 %_3000004, label %_4000000.0, label %_5000000.0
_4000000.0:
  ; ...
_5000000.0:
  %_5000002 = icmp slt i32 %_2, 0 ; n < 0
  br i1 %_5000002, label %_8000000.0, label %_9000000.0
_9000000.0:
  ;; ...
_21000000.0:
  ;; ...
_8000000.0:
  br label %_18000000.0
_18000000.0: ;; throw ArithmeticException
  %_18000001 = call dereferenceable_or_null(40) ptr @"scalanative_GC_alloc_small"(ptr @"_SM29java.lang.ArithmeticExceptionG4type", i64 40), !dbg !2922
  %_40000033 = getelementptr { { ptr }, ptr, ptr, ptr, i1, i1 }, { { ptr }, ptr, ptr, ptr, i1, i1 }* %_18000001, i32 0, i32 5
  %_40000034 = zext i1 true to i8
  store i8 %_40000034, ptr%_40000033, align 1
  %_40000036 = getelementptr { { ptr }, ptr, ptr, ptr, i1, i1 }, { { ptr }, ptr, ptr, ptr, i1, i1 }* %_18000001, i32 0, i32 4
  %_40000037 = zext i1 true to i8
  store i8 %_40000037, ptr%_40000036, align 1
  %_40000039 = getelementptr { { ptr }, ptr, ptr, ptr, i1, i1 }, { { ptr }, ptr, ptr, ptr, i1, i1 }* %_18000001, i32 0, i32 3
  store ptr @"_SM7__constG3-141", ptr%_40000039, align 8
  %_18000005 = call dereferenceable_or_null(40) ptr @"_SM19java.lang.ThrowableD16fillInStackTraceL19java.lang.ThrowableEO"(ptr nonnull dereferenceable(40) %_18000001), !dbg !2924
  br label %_19000000.0
_19000000.0:
  call ptr @"scalanative_throw"(ptr nonnull dereferenceable(40) %_18000001), !dbg !2933
  unreachable
_40000002.0: ;; throw null pointer exception
  call ptr @"_SM34scala.scalanative.runtime.package$D16throwNullPointernEO"(ptr null), !dbg !2934
  unreachable
_40000010.0:
  %_40000042 = phi i32 [%_9000002, %_40000022.0], [0, %_40000006.0]
  %_40000043 = phi i32 [%_40000021, %_40000022.0], [%_40000005, %_40000006.0]
  call ptr @"_SM34scala.scalanative.runtime.package$D16throwOutOfBoundsiinEO"(ptr null, i32 %_40000042, i32 %_40000043), !dbg !2934
  unreachable
}
```

</details>

**Comment by tanishiking** [comment] 2024-11-22 09:52
Ah, wait, `_bigInteger` should be initialized by the constructor https://github.com/scala/scala/blob/ff5c1546fc11b7ae9f5f7b37192000a5dc9f9c4b/src/library/scala/math/BigInt.scala#L204-L209

**Comment by tanishiking** [comment] 2024-11-23 00:01
Upstream PR is merged, this should be fixed in the next scalalib version

**Closed** 2024-11-25 09:00 UTC
Labels: bug
