### ISSUE TITLE
`\p{Alnum}` regex not working

### ISSUE THREAD

**Issue by armanbilge** [scala-native/scala-native#2793] opened 2022-08-20 09:42 UTC
```scala
@main def main =
  println("""\p{Alnum}""".r.matches("0"))
```

On JVM it returns `true`, on Native `false`. This is not a blocker since an easy workaround is to use `[A-Za-z0-9]`.

https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html

**Comment by LeeTibbert** [comment] 2022-08-21 22:32
Works on my system, I do not see what the issue is. Oh, wait, _this_ is the Issue ;-)

Thank you for the report and, especially, for the concise reproduction case.

I hope the PR fix works on your system.  I submitted it to the 0.4.x stream, with
the hope that it will be rolled forward into 0.5.0.

This was a good one.  Not only was it obscure to all but you who tripped over it,
it was also two complementary bugs.  The one in the base note and its
dual '\p{Alpha}" accepting digits when it should not.

After examining the code and suspecting a total air ball (miss), I
went to the re2j GitHub repository and examined the file there.
It confirmed my proposed fix, now in a PR.

CI obviously did not catch this case so I did manual testing.

I then enabled the extensive & time consuming regex `ExecTest`.
It has some 'alnum' tests but has never detected this defect.
The test past, showing that at least I did not break anything
obvious.  That test is for regex developers only and is _not_ 
a candidate for CI.

One small victory for this month...

**Comment by LeeTibbert** [comment] 2022-08-21 22:47
Arman,

Commenting on someone's regex is like commenting on someone's dog or children: unlikely
to bring profit or honor.

You probably are more than well aware that `\p{Alnum}` is ASCII only.  That may be what your 
application requires and you may be way ahead of me.

It is hidden in the Java `Pattern` documentation but Java 8 & mumble support Unicode blocks
for letters (L) and digits (D). 

Embarrassed by the defect in the base note, I checked during my study of this Issue to see if those work
 in Scala Native.
```
  println("Unicode blocks - Java style \\p{N}")
  println("\\p{N}".r.matches("0")) // true, matches spec                        
  println("\\p{L}".r.matches("A")) // true, matches spec    
```  
This may not be useful to you for this issue, but I hope it is 
useful to you someday.

Truth in advertising,  the Unicode tables in Scala Native regex
are old enough to vote.  Eric and I have has a long standing
desire to simplify & unify them with the more up to date
Unicode in Character (or punt the issue all together to
a library.  I have been following your SN ICU work with
interest.)

If you are searching for letters & digits, at least I do 
not have to loose sleep at night because the latest
emoticons are not present and you will not find them.

**Comment by armanbilge** [comment] 2022-08-21 22:50
Thanks for the fast fix and all the teachings 😁 

If it's of interest, I encountered the bug in question while porting this code:
https://github.com/http4s/http4s/blob/77e4f3adc73875ac62ea9def48542bdb58365868/tests/shared/src/test/scala/org/http4s/parser/ForwardedHeaderSpec.scala#L152

**Comment by LeeTibbert** [comment] 2022-08-21 23:12
Oh yeah,  I have not had a chance to check the Java spec for the 
950th time to see if they are supposed to work. When I was
in the code I noticed that the `\p{^Alnum}' negated form seemed
to be missing in the SN implementation.   It might be there
but if you get the suspicion that it is not, you are probably right.

**Comment by LeeTibbert** [comment] 2022-08-21 23:32
I checked the URL, I usually learn something from your postings.

I landed in two parsers in the same day. I must have kicked somebodies 
cat or regex or something with bad karma.

Guessing from `https` and reading the code, it looks like that code
is parsing HTTP headers.  From a quick lookup on the InterWeb it looks
like  RFC 2616 &  RFC 2396   constrain HTTP headers to be ASCII only.
So the regex looks OK for its context.

**Closed** 2022-08-29 12:36 UTC
Labels: has pr
