### ISSUE TITLE
Cannot convert Scala VarArg to CVararg

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-native/scala-native#647] opened 2017-04-19 18:40 UTC
I was thinking of implementing a basic java.util.Formatter using fprintf from c.

this is the scala signature

```
def format(formatStr: String, args: Array[AnyRef]): Formatter
```

this is the signature for sprintf

```
def sprintf(buffer: CString, format: CString, args: CVararg*): CInt = extern
```

It's not clear to me how to convert to a `CVararg*`

**Comment by MasseGuillaume** [comment] 2017-04-19 18:49
maybe one way to solve this is to have some compiler magic to create a va_list structure.

http://en.cppreference.com/w/cpp/io/c/vfprintf

**Comment by MasseGuillaume** [comment] 2017-04-19 19:48
It look like va_list is created by llvm itself.

http://llvm.org/docs/LangRef.html#variable-argument-handling-intrinsics

**Comment by densh** [comment] 2018-08-28 10:12
Duplicate of #1142

**Closed** 2018-08-28 10:39 UTC
