### ISSUE TITLE
Running a large number of unit tests results in EOFException

### ISSUE THREAD

**Issue by shadaj** [scala-native/scala-native#1008] opened 2017-09-10 18:28 UTC
When running unit tests for ScalaTest through Scala Native, a large number of tests is causing the Scala Native program to crash with the following exception:

```
[error] java.io.EOFException
[error] 	at java.lang.Throwable.init(Unknown Source)
[error] 	at java.lang.Exception.init(Unknown Source)
[error] 	at java.io.IOException.init(Unknown Source)
[error] 	at java.io.IOException.init(Unknown Source)
[error] 	at java.io.EOFException.init(Unknown Source)
[error] 	at java.io.EOFException.init(Unknown Source)
[error] 	at java.io.DataInputStream.readFully(Unknown Source)
[error] 	at java.io.DataInputStream.readFully(Unknown Source)
[error] 	at scala.scalanative.testinterface.TestMainBase.receive(Unknown Source)
[error] 	at scala.scalanative.testinterface.TestMainBase.testRunner(Unknown Source)
[error] 	at scala.scalanative.testinterface.TestMainBase.testMain(Unknown Source)
[error] 	at scala.scalanative.testinterface.TestMain$.main(Unknown Source)
[error] 	at <none>.main(Unknown Source)
```

The crash appears to be related to the high number of unit tests, as the tests run fine when enabled individually but the exception occurs when many tests are enabled at the same time. To reproduce, comment out one of the disabled test files in GenScalaTestNative.scala in https://github.com/scalatest/scalatest/pull/1185 and run `scalatestTestNative/test`.

**Comment by densh** [comment] 2017-09-11 16:05
Thanks for the report!

**Comment by muxanick** [comment] 2017-10-19 08:52
That could be related to the issue I found on windows branch, see how I fixed send/recv functions and it could be possible to use same code for all platforms:
https://github.com/muxanick/scala-native/blob/35981bb8b1d145f41879fb26289650176031893b/nativelib/src/main/resources/posix/sys/socket.c#L204

**Comment by ekrich** [comment] 2017-10-19 12:25
When you read the documentation of `recv` http://pubs.opengroup.org/onlinepubs/9699919799/functions/recv.html, it looks like you should check the return for `0` and `-1` so should it be up to the caller of `recv` to check and it depends on the flags passed to determine the behavior of the function. Maybe change this instead. https://github.com/scala-native/scala-native/blob/f929ea57b577ad9a6ca13db1105f0819e9f0dc82/javalib/src/main/scala/java/net/PlainSocketImpl.scala#L305-L319

**Comment by muxanick** [comment] 2017-10-19 17:29
@ekrich Sure thing, looks like ideal solution, but we need to change many places in code where user expects to read N bytes but received less than N bytes. In that case algorithm might have to be use stream-type containers.

**Comment by densh** [comment] 2018-01-09 13:03
@shadaj Given that native support has been merged to scalatest, is this not an issue any longer?

**Comment by shadaj** [comment] 2018-01-09 15:37
Last I checked, the issue still exists. We merged the support so that others can start using it, but never got to resolving the crash.

**Comment by ekrich** [comment] 2018-05-15 13:16
I can not get this to reproduce using "debug" or "release" with "immix" or "boehm". Does anyone have a reproducer?

**Comment by shadaj** [comment] 2018-05-17 15:45
@ekrich I had to generate thousands of unit tests to cause this issue. How many did you try to run with? I'll try to check again with ScalaTest later today.

**Closed** 2019-05-07 18:38 UTC
Labels: bug
