### ISSUE TITLE
"String".lines returns java.util.stream.Stream[String] on java 11 and 12

### ISSUE THREAD

**Issue by muxanick** [scala-native/scala-native#1680] opened 2019-08-05 23:24 UTC
```Scala
object Test {
  def strange(s: String): List[String] = {
    s.lines.iterator.asScala.toList
  }

  def main(args: Array[String]): Unit = {
    println(strange("line1\nline2\nline3"))
  }
}
```
it shows an error:
```Scala
> sandbox/run
[info] Updating {file:/bug/scala-native/}sandbox...
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[info] Compiling 1 Scala source to /bug/scala-native/sandbox/target/scala-2.11/classes...
[error] /bug/scala-native/sandbox/Test.scala:3: value toList is not a member of java.util.stream.Stream[String]
[error]     s.lines.toList
[error]             ^
[error] one error found
[error] (sandbox/compile:compileIncremental) Compilation failed
[error] Total time: 3 s, completed Aug 5, 2019, 3:54:55 PM
```
Workaround doesn't work as well:
```Scala
import scala.collection.JavaConverters._
object Test {
  def strange(s: String): List[String] = {
    s.lines.iterator.asScala.toList
  }

  def main(args: Array[String]): Unit = {
    println(strange("line1\nline2\nline3"))
  }
}
```

The real solution is to install Java 8 into classpath

**Comment by cryocz** [comment] 2019-08-06 19:41
I'm not entirely sure whether this is a related issue or not, but in my setup using `String#lines` compiles just fine. The issue is that I get a `UndefinedBehaviorError` exception at runtime. I'm using scala-native plugin `v0.4.0-M2`, via sbt `v1.2.8`. My java environment is:
```
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

**Comment by lolgab** [comment] 2020-01-10 21:22
This is issue is not Scala Native specific but is reported a Scala issue: https://github.com/scala/bug/issues/11125
I think we can close it here.

**Comment by sjrd** [comment] 2020-01-10 22:41
Yes, I agree.

**Closed by sjrd** 2020-01-10 22:41 UTC
