### ISSUE TITLE
cannot link: @Main$::main_scala.scalanative.runtime.ObjectArray_unit

### ISSUE THREAD

**Issue by xuwei-k** [scala-native/scala-native#887] opened 2017-06-30 01:20 UTC
### build.sbt

```scala
scalaVersion := "2.11.11"

enablePlugins(ScalaNativePlugin)
```

### src/main/scala/Main.scala

```scala
class Base {
  def main(args: Array[String]): Unit = {
    println("hello")
  }
}

object Main extends Base
```

### project/plugins.sbt

```
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.3.1")
```

`sbt run` fail in scala-native. success in JVM.

```
[info] Linking (1355 ms)
[error] cannot link: @Main$::main_scala.scalanative.runtime.ObjectArray_unit
[error] unable to link
[error] (compile:nativeLinkNIR) unable to link
[error] Total time: 4 s, completed Jun 30, 2017 10:15:06 AM
```

**Comment by matil019** [comment] 2017-06-30 02:11
I think it's another instance of #805.

**Comment by densh** [comment] 2017-06-30 07:54
That's definitely a duplicate of #805. 

Workaround: define an `override def main(args: Array[String]): Unit = super.main(args)` in `Main`.

**Closed by densh** 2017-06-30 07:54 UTC
