### ISSUE TITLE
Zone blocks fail compilation when return type is Ptr

### ISSUE THREAD

**Issue by nadavwr** [scala-native/scala-native#783] opened 2017-06-04 18:48 UTC
There are plenty of use cases where you may want to supply a `CString` to an extern method and expect a `Ptr` in return.

The following code is such an example:

```scala
import scala.scalanative.native._

@extern
@link("dl")
object dl {
  def dlopen(path: CString, mode: CInt): Ptr[Byte] = extern
}

object Sample extends App {
  val ptr: Ptr[Byte] =
    Zone { implicit alloc =>
      dl.dlopen(toCString("libm.dylib"), 1)
    }
  assert(ptr != null)
}
```

This fails with a frustrating "UnsupportedException: can't cast from Class(Top(java.lang.Object)) to Ptr (class java.lang.String)".

At first I wasn't sure what was causing this, so I added some printouts 

AsLowering.onInst:
```
     case inst @ Let(n, Op.As(to, Of(v, from))) =>
-      util.unsupported(s"can't cast from $from to $to")
+      util.unsupported(s"${inst.show}\ncan't cast from $from to $to")
```

Pass.onDefn:
```
     case defn @ Defn.Define(_, _, ty, insts) =>
-      defn.copy(ty = onType(ty), insts = onInsts(insts))
+      try {
+        defn.copy(ty = onType(ty), insts = onInsts(insts))
+      } catch {
+        case unsupported @ util.UnsupportedException(msg) =>
+          throw unsupported.copy(msg = msg + "\n\n" + defn.show)
+      }
```

So now the message provided by UnsupportedException is more informative:
```
%src.7 = as[ptr] %src.6 : class @java.lang.Object
can't cast from Class(Top(java.lang.Object)) to Ptr (class java.lang.String)

def @sample.Sample$::delayedEndpoint$sample$Sample$1_unit : (class @sample.Sample$) => unit {
%src.1(%src.0 : class @sample.Sample$):
  %src.2 = call[() => class @scala.scalanative.native.Zone$] @scala.scalanative.native.Zone$::load : ptr()
  %src.3 = classalloc @sample.Sample$$anonfun$1
  %src.4 = call[(class @sample.Sample$$anonfun$1) => unit] @sample.Sample$$anonfun$1::init : ptr(%src.3 : class @sample.Sample$$anonfun$1)
  %src.5 = method %src.2 : class @scala.scalanative.native.Zone$, @scala.scalanative.native.Zone$::apply_scala.Function1_java.lang.Object
  %src.6 = call[(class @scala.scalanative.native.Zone$, trait @scala.Function1) => class @java.lang.Object] %src.5 : ptr(%src.2 : class @scala.scalanative.native.Zone$, %src.3 : class @sample.Sample$$anonfun$1)
  %src.7 = as[ptr] %src.6 : class @java.lang.Object
  %src.8 = field %src.0 : class @sample.Sample$, @sample.Sample$::field.ptr
  %src.9 = store[ptr] %src.8 : ptr, %src.7 : ptr
  %src.10 = call[() => class @scala.Predef$] @scala.Predef$::load : ptr()
  %src.11 = method %src.0 : class @sample.Sample$, @sample.Sample$::ptr_ptr
  %src.12 = call[(class @sample.Sample$) => ptr] %src.11 : ptr(%src.0 : class @sample.Sample$)
  %src.13 = bitcast[ptr] null
  %src.14 = ine[ptr] %src.12 : ptr, %src.13 : ptr
  %src.15 = method %src.10 : class @scala.Predef$, @scala.Predef$::assert_bool_unit
  %src.16 = call[(class @scala.Predef$, bool) => unit] %src.15 : ptr(%src.10 : class @scala.Predef$, %src.14 : bool)
  ret unit
}
```

The instruction failing the compilation is the one starting with `%src.7`. We can look at the surrounding environment and see that we're looking at the `sample.Sample` (not so obvious in a larger codebase), and get a handwavy impression that the compiler wants the `Zone` to return a `java.lang.Object`—not the `Ptr[Byte]` we're expecting, hence the exception.

Workarounds I considered in the meanwhile are:
1) assigning the `Ptr` to an external variable
2) wrapping and extracting using a `case class BytePtrHolder(ptr: Ptr[Byte])`
3) handling the string allocation/release using try/finally

**Comment by nadavwr** [comment] 2017-06-04 19:18
Everything built against current master ([link](https://github.com/scala-native/scala-native/tree/67fa11f00af42a3b37214b21ffce0792eafb47ed))

**Comment by densh** [comment] 2017-06-05 12:57
This is another instance of #367, it seems like it's a blocker for zones to be useable, so I'll keep this issue for now.

**Comment by wookietreiber** [comment] 2017-12-06 22:20
I'm having a similar problem with this:

```scala
        Zone { implicit z =>
          val n = toCString(name)
          val v = stdlib.getenv(n)
          Option(v).map(fromCString(_)).getOrElse("")
        }
```

I'm not writing this as a "yeah, me too, please fix fix fix...", but to showcase a workaround: do not use `fromCString` in the function used by `Option.map`. I don't know if this actually helps, I just wanted to get the information out about the workaround:

```scala
        Zone { implicit z =>
          val n = toCString(name)
          val o = stdlib.getenv(n) match {
            case null  => None
            case value => Some(fromCString(value))
          }
          o.getOrElse("")
        }
```

**Comment by pbatko** [comment] 2018-01-11 21:09
Have another repro

```
%4 = as[ptr] %2 : class @java.lang.Object
```
```
[error] (sandbox/compile:nativeOptimizeNIR) scala.scalanative.util.UnsupportedException: can't cast from Class(Top(java.lang.Object)) to Ptr
```

Minimal
```
import scala.scalanative.native._

object Test {

  def main(args: Array[String]): Unit = {

    implicit val z: Zone = null
    val barFun: CString => Unit = a => fromCString(a)

  }
}
```

The problem is the cast in the bridge method

```
scala.runtime.AbstractFunction1 with Serializable {
  final def apply(a: scala.scalanative.native.Ptr): Unit = {
    scala.scalanative.native.`package`.fromCString(a, scala.scalanative.native.`package`.fromCString$default$2());
    ()
  };
  final <bridge> <artifact> def apply(v1: Object): Object = {
    anonfun$1.this.apply(v1.$asInstanceOf[scala.scalanative.native.Ptr]());
    scala.runtime.BoxedUnit.UNIT
  };
  def <init>(): <$anon: Function1> = {
    anonfun$1.super.<init>();
    ()
  }
}
```

```
override(@scala.Function1::apply_java.lang.Object_java.lang.Object) def @Test$$anonfun$1::apply_java.lang.Object_java.lang.Object : (class @Test$$anonfun$1, class @java.lang.Object) => class @java.lang.Object {
%3(%1 : class @Test$$anonfun$1, %2 : class @java.lang.Object):
  %4 = as[ptr] %2 : class @java.lang.Object
  %5 = method %1 : class @Test$$anonfun$1, @Test$$anonfun$1::apply_ptr_unit
  %6 = call[(class @Test$$anonfun$1, ptr) => unit] %5 : ptr(%1 : class @Test$$anonfun$1, %4 : ptr)
  ret unit
```

**Comment by pbatko** [comment] 2018-01-11 21:19
Is a solution to augment scalac to emit specialized implementation for `Ptr` and use boxing/unboxing for the bridge method?

E.g. for usual primitive types:

```
val fooFoo: Int => Double = a => a * 2.0
```

```
scala.runtime.AbstractFunction1$mcDI$sp with Serializable {
  final def apply(a: Int): Double = anonfun$1.this.apply$mcDI$sp(a);
  <specialized> def apply$mcDI$sp(a: Int): Double = a.*(2.0);
  final <bridge> <artifact> def apply(v1: Object): Object = scala.Double.box(anonfun$1.this.apply(scala.Int.unbox(v1)));
  def <init>(): <$anon: Function1> = {
    anonfun$1.super.<init>();
    ()
  }
}
```

**Comment by densh** [comment] 2018-01-12 12:28
@pbatko This one is tricky. It's another manifestation of #367 and is not easy to fix. The correct solution is to always box `Ptr` coming from scalac, but that requires optimizer to be smart enough to always remove those boxes (which we can't guarantee yet unfortunately).

**Comment by densh** [comment] 2018-08-28 10:37
Duplicate of #367.

**Closed by densh** 2018-08-28 10:37 UTC
Labels: bug, interop
