### ISSUE TITLE
Broken binary compatibility with 0.4.0 release

### ISSUE THREAD

**Issue by keynmol** [scala-native/scala-native#2190] opened 2021-03-04 18:29 UTC
SN: 0.4.0
OS: Ubuntu 20.04
Scala: 2.13.4

Forgive me if the title is vague, I just got a self-contained repro, not sure what the exact issue is.

This code:

```scala
abstract class TestStuff(stuff: String) {
  def main(args: Array[String]) = {
    println(stuff)
  }
}

object Hello extends TestStuff("hello")
``` 

Fails during linking stage:

```
[info] Linking (1604 ms)
[error] missing symbols:
[error] * M6Hello$D4mainLAL16java.lang.String_uEO
[error] unable to link
[error] (testNative / Compile / nativeLink) unable to link
```

I've set up a repository and CI to demonstrate that it only fails on SN: https://github.com/keynmol/scala-native-repro-2/runs/2033688964?check_suite_focus=true#step:5:213

---

I've also tested it on master: 

```
[info] Linking (666 ms)
[error] missing symbols:
[error] * M34scala.scalanative.runtime.package$D7toClassR_L15java.lang.ClassEO
[error] * M6Hello$D4mainLAL16java.lang.String_uEO
[error] unable to link
[error] (testNative / Compile / nativeLink) unable to link
```

Context: spotted it while trying to port decline, which does stuff like this to handle main method and options parsing.

**Comment by WojciechMazur** [comment] 2021-03-05 09:18
Thank you for creating this issue. It's a known problem with pending PR #1984. It should be included in 0.4.1. 
Until then you can workaround this issue using the following main method override: 
```
  override def main(args: Array[String]) = super.main(args)
```

**Comment by WojciechMazur** [comment] 2021-03-05 09:33
I was going to close this issue and mark this as duplicate, although your case is also showing binary incompatibility between 0.4.0 and 0.4.1-SNAPSHOT. 
I have seen that in the reproduction project you have not used any external libraries, am I correct? 
I guess that you might have compiled code using 0.4.0, and then switched to 0.4.1-SNAPSHOT (current master). You have not removed the results of the previous compilation, so sbt plugin tried omitted compilation and went straight to linking using NIR files from 0.4.0. Is such a scenario possible?
In #2139 we have removed `scala.scalanative.runtime.package::toClass(RawPtr): Class[_]` method as Denys has found a better and more performant solution. However, we should not remove this method entirely. We need to restore, mark it internally as deprecated and remove it in the next major release.  

@keynmol thank you once again for creating this issue, I hope you won't mind if I would rename it to describe the binary incompatibility issue, since the root problem you're dealing with already exists in other issue.

**Comment by keynmol** [comment] 2021-03-05 13:00
> went straight to linking using NIR files from 0.4.0. Is such a scenario possible?

I think it is, although I would've expected that reloading SBT to pick up new plugin would invalidate those - I will try this scenario explicitly.

> It's a known problem with pending PR #1984

a-ha! Didn't do my due diligence properly :) I will try from the branch and see if it fixes it.

**Closed** 2021-09-30 07:52 UTC
Labels: blocker
